export interface EpirocPanne {
  id: string;
  system: string;
  title: string;
  titleEn: string;
  titleEs: string;
  severity: "VERT" | "JAUNE" | "ROUGE";
  symptoms: string;
  symptomsEn: string;
  symptomsEs: string;
  cause: string;
  causeEn: string;
  causeEs: string;
  action: string;
  actionEn: string;
  actionEs: string;
  repTime: number; // in hours
}

export const EPIROC_SYSTEMS = [
  { id: "SYS1", label: "MOTEUR", icon: "Flame" },
  { id: "SYS2", label: "TRANSMISSION", icon: "Shuffle" },
  { id: "SYS3", label: "HYDRAULIQUE", icon: "Droplet" },
  { id: "SYS4", label: "DIRECTION & ARTICULATION", icon: "Compass" },
  { id: "SYS5", label: "FREINAGE SAHR", icon: "ShieldAlert" },
  { id: "SYS6", label: "ÉLECTRIQUE", icon: "Zap" },
  { id: "SYS7", label: "REFROIDISSEMENT", icon: "ThermometerSnowflake" },
  { id: "SYS8", label: "ÉCHAPPEMENT & VENTILATION", icon: "Wind" },
  { id: "SYS9", label: "CHÂSSIS & ROUES", icon: "Disc" },
  { id: "SYS10", label: "GODET, BOOM & GRAISSAGE", icon: "Hammer" },
  { id: "SYS11", label: "SÉCURITÉ & ANSUL", icon: "ShieldCheck" }
];

export const EPIROC_PANNES: EpirocPanne[] = [
  // SYSTEME 1 - MOTEUR
  {
    id: "1.1.1.A",
    system: "SYS1",
    title: "ECM ne communique pas (pas de démarrage, pas de codes)",
    titleEn: "ECM not communicating (no start, no fault codes)",
    titleEs: "ECM no comunica (sin arranque, sin códigos de falla)",
    severity: "ROUGE",
    symptoms: "Démarreur tourne mais pas d'allumage. Tableau de bord n'affiche aucun régime moteur.",
    symptomsEn: "Starter cranks but no ignition. Dashboard displays no engine RPM.",
    symptomsEs: "El motor gira pero no enciende. El tablero no muestra RPM del motor.",
    cause: "Défaut d'alimentation 24V de l'ECM, fusible bus grillé ou masse déconnectée.",
    causeEn: "Faulty 24V power supply to ECM, blown bus fuse or disconnected ground.",
    causeEs: "Falla de alimentación de 24V al ECM, fusible fundido o masa desconectada.",
    action: "Vérifier le fusible CAN bus 10A et nettoyer le point de raccordement de la masse de l'ECM.",
    actionEn: "Check the 10A CAN bus fuse and clean the ECM ground terminal.",
    actionEs: "Verificar el fusible CAN bus de 10A y limpiar el terminal de tierra del ECM.",
    repTime: 1.5
  },
  {
    id: "1.1.1.B",
    system: "SYS1",
    title: "Capteur régime vilebrequin (SPN 111 / FMI 2)",
    titleEn: "Crankshaft position sensor fault (SPN 111 / FMI 2)",
    titleEs: "Fallo sensor de posición del cigüeñal (SPN 111 / FMI 2)",
    severity: "JAUNE",
    symptoms: "Démarrage difficile, ralenti instable, baisse de puissance significative.",
    symptomsEn: "Hard starting, rough idle, significant loss of power.",
    symptomsEs: "Arranque difícil, ralentí inestable, pérdida significativa de potencia.",
    cause: "Jeu d'entrefer excessif sur la cible ou débris métalliques sur la tête magnétique.",
    causeEn: "Excessive air gap on target or metallic debris on the magnetic head.",
    causeEs: "Holgura excesiva en el objetivo o residuos metálicos en el cabezal magnético.",
    action: "Nettoyer le capteur, régler l'entrefer à 1.0 mm, remplacer le capteur si défectueux.",
    actionEn: "Clean sensor, adjust air gap to 1.0 mm, replace sensor if defective.",
    actionEs: "Limpiar el sensor, ajustar holgura a 1.0 mm, reemplazar sensor si está defectuoso.",
    repTime: 0.8
  },
  {
    id: "1.1.1.C",
    system: "SYS1",
    title: "Capteur pression rail (SPN 157 / FMI 3)",
    titleEn: "Fuel rail pressure sensor (SPN 157 / FMI 3)",
    titleEs: "Sensor de presión de riel (SPN 157 / FMI 3)",
    severity: "JAUNE",
    symptoms: "Mode dégradé activé, limite régime à 1200 rpm, voyant jaune allumé.",
    symptomsEn: "Limp mode active, engine speed limited to 1200 rpm, amber light on.",
    symptomsEs: "Modo degradado activo, velocidad limitada a 1200 rpm, luz ámbar encendida.",
    cause: "Tension trop élevée sur le faisceau du capteur ou court-circuit interne.",
    causeEn: "High voltage signal on sensor harness or internal short circuit.",
    causeEs: "Señal de alto voltaje en el mazo del sensor o cortocircuito interno.",
    action: "Mesurer la tension d'alimentation de 5V, remplacer le capteur de pression de rail.",
    actionEn: "Measure 5V reference voltage, replace fuel rail pressure sensor.",
    actionEs: "Medir el voltaje de referencia de 5V, reemplazar el sensor de presión de riel.",
    repTime: 1.0
  },
  {
    id: "1.1.2.A",
    system: "SYS1",
    title: "Pompe haute pression Common Rail défectueuse",
    titleEn: "Common Rail high-pressure pump failure",
    titleEs: "Fallo bomba de alta presión Common Rail",
    severity: "ROUGE",
    symptoms: "Arrêt complet du moteur sous charge, refus de redémarrer.",
    symptomsEn: "Engine stalls completely under load, refuses to restart.",
    symptomsEs: "El motor se apaga bajo carga, se niega a reiniciar.",
    cause: "Contamination par l'eau dans le gasoil provoquant le grippage des pistons internes.",
    causeEn: "Water contamination in diesel fuel leading to internal piston seizure.",
    causeEs: "Contaminación por agua en el diesel que provoca el gripado de los pistones.",
    action: "Vider le filtre séparateur d'eau, remplacer la pompe HP et rincer le réservoir.",
    actionEn: "Drain water separator filter, replace HP pump, flush fuel tank.",
    actionEs: "Drenar filtro separador de agua, reemplazar bomba de alta presión, enjuagar tanque.",
    repTime: 4.5
  },
  {
    id: "1.1.2.B",
    system: "SYS1",
    title: "Injecteur bloqué ouvert/fermé (fumée noire, ratés)",
    titleEn: "Injector stuck open/closed (black smoke, misfire)",
    titleEs: "Inyector atascado abierto/cerrado (humo negro, fallos)",
    severity: "ROUGE",
    symptoms: "Bruit de claquement métallique lourd, fumée noire épaisse à l'échappement.",
    symptomsEn: "Heavy metallic knocking sound, thick black smoke at exhaust.",
    symptomsEs: "Golpeteo metálico pesado, humo negro espeso en el escape.",
    cause: "Particule abrasive ayant bloqué l'aiguille de l'injecteur en position ouverte.",
    causeEn: "Abrasive particle blocking the injector needle in open position.",
    causeEs: "Partícula abrasiva que bloquea la aguja del inyector en posición abierta.",
    action: "Identifier le cylindre via test d'exclusion électronique, remplacer l'injecteur.",
    actionEn: "Identify cylinder via electronic cut-out test, replace faulty injector.",
    actionEs: "Identificar cilindro mediante prueba de corte electrónica, reemplazar inyector.",
    repTime: 3.0
  },
  {
    id: "1.1.3.A",
    system: "SYS1",
    title: "Thermostat bloqué fermé (surchauffe)",
    titleEn: "Thermostat stuck closed (overheating)",
    titleEs: "Termostato atascado cerrado (sobrecalentamiento)",
    severity: "ROUGE",
    symptoms: "Température liquide de refroidissement atteint 105°C en moins de 10 min de marche.",
    symptomsEn: "Coolant temperature reaches 105°C in less than 10 mins of operation.",
    symptomsEs: "La temperatura del refrigerante alcanza los 105°C en menos de 10 minutos.",
    cause: "Élément thermostatique à cire défaillant empêchant l'ouverture vers le radiateur.",
    causeEn: "Wax pellet failure preventing flow opening to the radiator.",
    causeEs: "Falla del elemento de cera que impide el flujo hacia el radiador.",
    action: "Remplacer impérativement le thermostat par un neuf. Ne jamais tourner sans.",
    actionEn: "Replace thermostat immediately. Never run the engine without a thermostat.",
    actionEs: "Reemplazar termostato de inmediato. Nunca hacer funcionar el motor sin él.",
    repTime: 1.2
  },
  {
    id: "1.1.3.B",
    system: "SYS1",
    title: "Thermostat bloqué ouvert (moteur ne chauffe pas)",
    titleEn: "Thermostat stuck open (engine won't warm up)",
    titleEs: "Termostato atascado abierto (el motor no se calienta)",
    severity: "VERT",
    symptoms: "Température d'eau reste sous 60°C même après 1h d'utilisation intensive.",
    symptomsEn: "Coolant temperature remains below 60°C even after 1h of heavy use.",
    symptomsEs: "La temperatura permanece por debajo de 60°C incluso tras 1h de uso pesado.",
    cause: "Ressort de rappel cassé maintenant le clapet en position ouverte en continu.",
    causeEn: "Broken return spring keeping the valve in open position constantly.",
    causeEs: "Resorte de retorno roto que mantiene la válvula abierta constantemente.",
    action: "Remplacer le thermostat au prochain arrêt d'entretien programmé.",
    actionEn: "Replace thermostat during next scheduled maintenance window.",
    actionEs: "Reemplazar termostato en la próxima ventana de mantenimiento programada.",
    repTime: 1.2
  },
  {
    id: "1.1.3.C",
    system: "SYS1",
    title: "Fuite liquide refroidissement (durite, radiateur, joint culasse)",
    titleEn: "Coolant leak (hose, radiator, cylinder head joint)",
    titleEs: "Fuga de refrigerante (manguera, radiador, culata)",
    severity: "JAUNE",
    symptoms: "Niveau bas dans le vase d'expansion, vapeur d'eau sous le capot.",
    symptomsEn: "Low expansion tank level, water vapor visible under hood.",
    symptomsEs: "Nivel bajo en el tanque de expansión, vapor bajo el capó.",
    cause: "Collier desserré, fissure de fatigue thermique du radiateur ou joint de culasse HS.",
    causeEn: "Loose clamp, thermal fatigue crack in radiator or blown head gasket.",
    causeEs: "Abrazadera floja, grieta por fatiga térmica en radiador o junta de culata dañada.",
    action: "Localiser la fuite, resserrer les colliers, réparer ou remplacer la durite.",
    actionEn: "Locate leak, retighten clamps, repair or replace the cooling hose.",
    actionEs: "Localizar fuga, apretar abrazaderas, reparar o reemplazar la manguera.",
    repTime: 1.5
  },
  {
    id: "1.1.4.A",
    system: "SYS1",
    title: "Pression huile moteur basse (SPN 100 / FMI 1)",
    titleEn: "Low engine oil pressure (SPN 100 / FMI 1)",
    titleEs: "Presión baja de aceite de motor (SPN 100 / FMI 1)",
    severity: "ROUGE",
    symptoms: "Voyant rouge allumé fixe, alarme sonore continue, arrêt automatique moteur.",
    symptomsEn: "Solid red warning light, continuous buzzer, automatic engine shutdown.",
    symptomsEs: "Luz roja encendida, alarma sonora continua, parada de motor automática.",
    cause: "Niveau d'huile critique, pompe à huile usée ou crépine d'aspiration colmatée.",
    causeEn: "Critical oil level, worn oil pump or clogged pickup screen.",
    causeEs: "Nivel crítico de aceite, bomba de aceite desgastada o colador obstruido.",
    action: "🛑 ARRÊT IMMÉDIAT. Vérifier le niveau d'huile, mesurer la pression réelle au manomètre.",
    actionEn: "🛑 STOP IMMEDIATELY. Check oil level, measure actual pressure with mechanical gauge.",
    actionEs: "🛑 PARADA INMEDIATA. Verificar nivel, medir presión real con un manómetro.",
    repTime: 2.0
  },
  {
    id: "1.1.4.B",
    system: "SYS1",
    title: "Fuite huile moteur externe",
    titleEn: "External engine oil leak",
    titleEs: "Fuga externa de aceite de motor",
    severity: "JAUNE",
    symptoms: "Traces d'huile noire sous le carter moteur, baisse progressive de jauge.",
    symptomsEn: "Black oil traces under oil pan, progressive oil level decline.",
    symptomsEs: "Trazas de aceite negro bajo el cárter, descenso progresivo del nivel.",
    cause: "Joint spi de vilebrequin défectueux ou vis de carter desserrées.",
    causeEn: "Defective crankshaft seal or loose oil pan bolts.",
    causeEs: "Sello de cigüeñal defectuoso o pernos del cárter de aceite flojos.",
    action: "Resserrer le carter, nettoyer le moteur pour isoler et changer le joint défectueux.",
    actionEn: "Retighten oil pan bolts, clean engine to isolate leak, replace leaking seal.",
    actionEs: "Apretar pernos del cárter, limpiar para aislar la fuga y cambiar retén.",
    repTime: 3.5
  },
  {
    id: "1.1.5.A",
    system: "SYS1",
    title: "Turbo grippé / play excessif",
    titleEn: "Turbocharger seized / excessive shaft play",
    titleEs: "Turbocompresor gripado / holgura de eje excesiva",
    severity: "ROUGE",
    symptoms: "Manque de puissance total, sifflement strident ou fumée bleue/noire.",
    symptomsEn: "Total loss of power, loud high-pitched whistle or blue/black smoke.",
    symptomsEs: "Pérdida total de potencia, silbido agudo o humo azul/negro.",
    cause: "Défaut de lubrification sous haute température ou pénétration de corps étranger.",
    causeEn: "Lack of lubrication under high temperatures or foreign object ingestion.",
    causeEs: "Falta de lubricación bajo altas temperaturas o ingreso de objeto extraño.",
    action: "Vérifier le jeu axial de la turbine. Remplacer le turbo, changer l'huile et les filtres.",
    actionEn: "Check shaft axial play. Replace turbocharger, change engine oil and filters.",
    actionEs: "Verificar juego axial. Reemplazar turbo, cambiar aceite y filtros.",
    repTime: 4.0
  },
  {
    id: "1.1.5.B",
    system: "SYS1",
    title: "Filtre air colmaté",
    titleEn: "Clogged air filter",
    titleEs: "Filtro de aire obstruido",
    severity: "JAUNE",
    symptoms: "Perte de puissance, fumée noire à l'accélération, indicateur colmatage rouge.",
    symptomsEn: "Loss of power, black smoke during acceleration, red restriction gauge.",
    symptomsEs: "Pérdida de potencia, humo negro al acelerar, indicador de restricción en rojo.",
    cause: "Atmosphère de mine chargée de poussières de forage sans nettoyage fréquent.",
    causeEn: "Dusty mine atmosphere without regular filter servicing.",
    causeEs: "Atmósfera de mina cargada de polvo sin mantenimiento regular del filtro.",
    action: "Remplacer l'élément filtrant primaire. Nettoyer l'enceinte du filtre.",
    actionEn: "Replace primary filter element. Clean filter housing container.",
    actionEs: "Reemplazar elemento filtrante primario. Limpiar la carcasa del filtro.",
    repTime: 0.3
  },
  {
    id: "1.1.6.A",
    system: "SYS1",
    title: "Préchauffage défectueux (démarrage impossible par froid)",
    titleEn: "Preheating failure (hard cold start)",
    titleEs: "Fallo de precalentamiento (arranque en frío difícil)",
    severity: "VERT",
    symptoms: "Démarrage laborieux le matin avec fumée blanche de carburant imbrûlé.",
    symptomsEn: "Difficult cold start in morning with white smoke from unburnt fuel.",
    symptomsEs: "Arranque difícil por la mañana con humo blanco de combustible no quemado.",
    cause: "Bougies de préchauffage grillées ou relais de commande de puissance HS.",
    causeEn: "Burnt glow plugs or failed power control relay.",
    causeEs: "Bujías de precalentamiento quemadas o relé de control dañado.",
    action: "Tester la résistance des bougies (norme < 1 Ohm), remplacer le relais.",
    actionEn: "Check glow plug resistance (< 1 Ohm is normal), replace relay if open.",
    actionEs: "Probar resistencia de bujías (norma < 1 Ohm), reemplazar relé si falla.",
    repTime: 1.0
  },

  // SYSTEME 2 - TRANSMISSION
  {
    id: "2.1.1.A",
    system: "SYS2",
    title: "Pompe hydrostatique principale grippée",
    titleEn: "Main hydrostatic pump seized",
    titleEs: "Bomba hidrostática principal gripada",
    severity: "ROUGE",
    symptoms: "La machine ne bouge plus du tout dans aucun sens. Moteur cale au passage du rapport.",
    symptomsEn: "Machine does not move in either direction. Engine stalls when gear engaged.",
    symptomsEs: "La máquina no se mueve en ninguna dirección. El motor se apaga al embragar.",
    cause: "Surchauffe d'huile hydraulique extrême ou cavitation prolongée due à un niveau bas.",
    causeEn: "Extreme hydraulic oil overheating or prolonged cavitation due to low oil level.",
    causeEs: "Sobrecalentamiento extremo del aceite o cavitación por nivel bajo.",
    action: "Remplacer l'ensemble de la pompe hydrostatique, rincer tout le circuit de translation.",
    actionEn: "Replace entire hydrostatic pump assembly, flush the travel hydraulic circuit.",
    actionEs: "Reemplazar conjunto de bomba hidrostática, enjuagar circuito de traslación.",
    repTime: 8.0
  },
  {
    id: "2.1.1.B",
    system: "SYS2",
    title: "Pompe hydrostatique fuite interne",
    titleEn: "Hydrostatic pump internal leak",
    titleEs: "Fuga interna de bomba hidrostática",
    severity: "JAUNE",
    symptoms: "La machine perd de la vitesse en rampe à chaud. Pression de gavage faiblarde.",
    symptomsEn: "Machine loses speed on ramps when hot. Low charge pressure.",
    symptomsEs: "La máquina pierde velocidad en rampas en caliente. Baja presión de carga.",
    cause: "Usure des patins de pistons de la pompe ou rayures sur la glace de distribution.",
    causeEn: "Worn pump piston shoes or scratches on the valve plate.",
    causeEs: "Desgaste de los patinos de pistón de bomba o rayas en la placa de válvulas.",
    action: "Tester le débit de retour de drain. Déposer la pompe pour reconditionnement.",
    actionEn: "Test drain port leakage flow rate. Remove pump for rebuild.",
    actionEs: "Probar caudal de fuga del drenaje. Desmontar bomba para reconstrucción.",
    repTime: 6.0
  },
  {
    id: "2.1.2.A",
    system: "SYS2",
    title: "Moteur hydrostatique translation grippé",
    titleEn: "Hydrostatic travel motor seized",
    titleEs: "Motor hidrostático de traslación gripado",
    severity: "ROUGE",
    symptoms: "Roues bloquées mécaniquement, bruits de craquement métallique intense.",
    symptomsEn: "Wheels locked mechanically, intense metallic crackling noise.",
    symptomsEs: "Ruedas bloqueadas mecánicamente, ruido de crujido metálico intenso.",
    cause: "Rupture interne du bloc cylindre du moteur hydrostatique de roue.",
    causeEn: "Internal failure of the wheel hydrostatic motor cylinder block.",
    causeEs: "Rotura interna del bloque de cilindros del motor hidrostático de rueda.",
    action: "Déposer le moteur de translation, contrôler la limaille, remplacer le bloc moteur.",
    actionEn: "Remove travel motor, check for metal debris, replace motor block.",
    actionEs: "Desmontar motor de traslación, revisar limaduras, reemplazar bloque.",
    repTime: 5.5
  },
  {
    id: "2.2.1.A",
    system: "SYS2",
    title: "Essieu avant bruyant (roulements, différentiel)",
    titleEn: "Noisy front axle (bearings, differential)",
    titleEs: "Eje delantero ruidoso (rodamientos, diferencial)",
    severity: "JAUNE",
    symptoms: "Grondement sourd proportionnel à la vitesse d'avancement de la machine.",
    symptomsEn: "Low rumble proportional to the travel speed of the machine.",
    symptomsEs: "Zumbido sordo proporcional a la velocidad de avance de la máquina.",
    cause: "Manque de lubrification dans l'essieu ou jeu de denture de couple conique déréglé.",
    causeEn: "Lack of axle lubrication or incorrect bevel gear backlash setting.",
    causeEs: "Falta de lubricación en el eje o juego de piñón y corona desajustado.",
    action: "Vidanger l'essieu, inspecter la limaille sur le bouchon magnétique, ajuster le jeu.",
    actionEn: "Drain axle, inspect magnetic plug for metal shaving, adjust gear backlash.",
    actionEs: "Vaciar aceite de eje, revisar tapón magnético, ajustar juego de engranajes.",
    repTime: 4.0
  },
  {
    id: "2.2.3.A",
    system: "SYS2",
    title: "Pont avant fuite huile",
    titleEn: "Front axle oil leak",
    titleEs: "Fuga de aceite de eje delantero",
    severity: "VERT",
    symptoms: "Suintement continu d'huile de pont au niveau du nez de pont ou des réducteurs.",
    symptomsEn: "Continuous gear oil weeping around input pinion or wheel hubs.",
    symptomsEs: "Goteo continuo de aceite en el piñón de entrada o cubos de rueda.",
    cause: "Joint à lèvre usé par la poussière abrasive de mine pénétrant les arbres.",
    causeEn: "Radial oil seal worn by abrasive mine dust entering shaft sleeves.",
    causeEs: "Retén desgastado por el polvo abrasivo de la mina que penetra los ejes.",
    action: "Remplacer le joint spi d'entrée de pont ou les joints toriques de moyeux.",
    actionEn: "Replace front axle input seal or hub O-rings.",
    actionEs: "Reemplazar el retén de entrada del puente o juntas tóricas de cubos.",
    repTime: 2.5
  },
  {
    id: "2.5.1.A",
    system: "SYS2",
    title: "Chaîne transmission avant allongée/cassée",
    titleEn: "Front transmission chain stretched/broken",
    titleEs: "Cadena de transmisión delantera estirada/rota",
    severity: "ROUGE",
    symptoms: "Perte totale de traction sur l'essieu avant, grand bruit d'impact sous la cabine.",
    symptomsEn: "Total loss of traction on front axle, loud impact sound under cabin.",
    symptomsEs: "Pérdida total de tracción en eje delantero, fuerte ruido bajo cabina.",
    cause: "Fatigue mécanique, manque chronique de lubrification ou surcharge de poussée.",
    causeEn: "Mechanical fatigue, chronic lack of lubrication or severe thrust overload.",
    causeEs: "Fatiga mecánica, falta crónica de lubricación o sobrecarga severa.",
    action: "Changer la chaîne complète de transmission avant. Remplacer les pignons usés.",
    actionEn: "Replace entire front drive chain. Replace worn sprockets too.",
    actionEs: "Cambiar cadena de transmisión delantera completa. Reemplazar piñones.",
    repTime: 4.5
  },
  {
    id: "2.5.1.B",
    system: "SYS2",
    title: "Chaîne transmission avant bruyante",
    titleEn: "Front drive chain noisy",
    titleEs: "Cadena de transmisión delantera ruidosa",
    severity: "JAUNE",
    symptoms: "Claquements répétitifs et saccadés lors des inversions de marche.",
    symptomsEn: "Repetitive knocking sounds during direction reversals.",
    symptomsEs: "Golpeteos repetitivos al invertir el sentido de marcha.",
    cause: "Tension insuffisante de la chaîne, maillons grippés ou guides usés.",
    causeEn: "Insufficient chain tension, seized links or worn chain guides.",
    causeEs: "Tensión insuficiente de cadena, eslabones gripados o guías desgastadas.",
    action: "Régler la tension de la chaîne, lubrifier abondamment, changer les guides.",
    actionEn: "Adjust chain tension, lubricate heavily, replace chain guides.",
    actionEs: "Ajuster tensión de cadena, lubricar abundantemente, cambiar guías.",
    repTime: 2.0
  },
  {
    id: "2.6.1.A",
    system: "SYS2",
    title: "Joint cardan articulation usé",
    titleEn: "Articulation cardan joint worn",
    titleEs: "Junta cardán de articulación desgastada",
    severity: "JAUNE",
    symptoms: "Vibrations notables sous le siège de l'opérateur en haute vitesse.",
    symptomsEn: "Noticeable vibrations felt under operator seat at higher travel speeds.",
    symptomsEs: "Vibraciones notables bajo el asiento del operador a alta velocidad.",
    cause: "Absence de graissage sur le croisillon de cardan ayant provoqué du jeu.",
    causeEn: "Lack of grease on cardan spider causing excessive mechanical play.",
    causeEs: "Ausencia de engrase en la cruceta de cardán que provoca juego mecánico.",
    action: "Remplacer le croisillon de cardan d'articulation. Graisser régulièrement.",
    actionEn: "Replace the articulation cardan joint spider. Lubricate regularly.",
    actionEs: "Reemplazar la cruceta de cardán de articulación. Engrasar regularmente.",
    repTime: 3.0
  },

  // SYSTEME 3 - HYDRAULIQUE
  {
    id: "3.1.1.A",
    system: "SYS3",
    title: "Pompe principale grippée",
    titleEn: "Main hydraulic pump seized",
    titleEs: "Bomba hidráulica principal gripada",
    severity: "ROUGE",
    symptoms: "Plus aucun mouvement de vérin ni de direction. Sifflement lourd du moteur.",
    symptomsEn: "No cylinder movement or steering. Heavy engine lugging and whining.",
    symptomsEs: "Sin movimiento de cilindros ni dirección. Silbido pesado del motor.",
    cause: "Pénétration de sable de forage ou niveau d'huile insuffisant.",
    causeEn: "Ingress of drilling dust/silica sand or critical oil starvation.",
    causeEs: "Ingreso de arena de perforación o nivel de aceite insuficiente.",
    action: "Déposer la pompe principale, nettoyer le réservoir, changer les filtres.",
    actionEn: "Remove main pump, flush hydraulic tank, replace all system filters.",
    actionEs: "Desmontar bomba principal, limpiar tanque, cambiar filtros.",
    repTime: 5.0
  },
  {
    id: "3.1.1.B",
    system: "SYS3",
    title: "Pompe principale fuite interne",
    titleEn: "Main pump internal leak",
    titleEs: "Fuga interna de bomba principal",
    severity: "JAUNE",
    symptoms: "Les mouvements du godet et du boom ralentissent à mesure que l'huile chauffe.",
    symptomsEn: "Bucket and boom movements slow down progressively as oil temperature rises.",
    symptomsEs: "Los movimientos de godet y boom se ralentizan al calentarse el aceite.",
    cause: "Usure normale par friction interne ou surpression fréquente.",
    causeEn: "Normal wear by internal friction or frequent pressure relief bypass.",
    causeEs: "Desgaste normal por fricción interna o sobrepresión frecuente.",
    action: "Contrôler le débit de retour de drain. Reconditionner la pompe.",
    actionEn: "Check case drain leakage flow rate. Recondition/rebuild pump.",
    actionEs: "Revisar caudal de retorno de drenaje. Reacondicionar la bomba.",
    repTime: 4.5
  },
  {
    id: "3.1.2.A",
    system: "SYS3",
    title: "Filtre retour colmaté",
    titleEn: "Return filter clogged",
    titleEs: "Filtro de retorno obstruido",
    severity: "JAUNE",
    symptoms: "Voyant filtre colmaté allumé, pression excessive dans le carter de pompe.",
    symptomsEn: "Clogged filter warning lamp active, high pressure in pump casing.",
    symptomsEs: "Luz de filtro obstruido encendida, presión alta en el cárter de bomba.",
    cause: "Accumulation de contaminants ou débris d'usure de vérin.",
    causeEn: "Contaminants accumulation or wear debris from cylinder rods.",
    causeEs: "Acumulación de contaminantes o residuos de desgaste de cilindros.",
    action: "Remplacer la cartouche filtrante de retour immédiatement.",
    actionEn: "Replace the return hydraulic filter cartridge immediately.",
    actionEs: "Reemplazar el cartucho filtrante de retorno de inmediato.",
    repTime: 0.5
  },
  {
    id: "3.2.1.A",
    system: "SYS3",
    title: "Charge pump défectueuse (pas de frein + pas de direction)",
    titleEn: "Charge pump defective (no brakes + no steering)",
    titleEs: "Bomba de carga defectuosa (sin freno + sin dirección)",
    severity: "ROUGE",
    symptoms: "Impossibilité de relâcher les freins (machine bloquée), direction dure.",
    symptomsEn: "Cannot release brakes (machine locked), extremely heavy steering.",
    symptomsEs: "Imposible liberar frenos (máquina bloqueada), dirección muy dura.",
    cause: "Fissure de l'engrenage interne ou arbre de pompe de charge cassé.",
    causeEn: "Cracked internal gear or broken charge pump drive shaft.",
    causeEs: "Fisura del engranaje interno o eje de bomba de carga roto.",
    action: "Changer la pompe de gavage/charge accouplée à la pompe principale.",
    actionEn: "Replace the charge/gavage pump coupled with the main pump.",
    actionEs: "Cambiar la bomba de carga acoplada a la bomba principal.",
    repTime: 3.5
  },
  {
    id: "3.3.1.A",
    system: "SYS3",
    title: "Vérin hoist gauche fuite externe",
    titleEn: "Left hoist cylinder external leak",
    titleEs: "Fuga externa cilindro hoist izquierdo",
    severity: "JAUNE",
    symptoms: "Perte visible d'huile hydraulique le long du fût du vérin.",
    symptomsEn: "Visible loss of hydraulic oil dripping along cylinder barrel.",
    symptomsEs: "Pérdida visible de aceite a lo largo del cilindro hoist.",
    cause: "Joint racleur et joint de tige endommagés par la poussière ou projection.",
    causeEn: "Wiper and rod seals damaged by drilling dust or rock impacts.",
    causeEs: "Retén de vástago dañado por el polvo o impactos de roca.",
    action: "Déposer le vérin gauche et remplacer le kit complet de joints de nez.",
    actionEn: "Remove left cylinder and replace the complete rod seal kit.",
    actionEs: "Desmontar cilindro izquierdo y reemplazar el kit de juntas.",
    repTime: 2.5
  },
  {
    id: "3.3.1.B",
    system: "SYS3",
    title: "Vérin hoist gauche fuite interne",
    titleEn: "Left hoist cylinder internal leak",
    titleEs: "Fuga interna cilindro hoist izquierdo",
    severity: "JAUNE",
    symptoms: "Le boom descend lentement tout seul sous charge (dérive hydraulique).",
    symptomsEn: "The boom drifts down slowly on its own under load (hydraulic drift).",
    symptomsEs: "El boom desciende lentamente solo bajo carga (deriva hidráulica).",
    cause: "Joint de piston interne endommagé ou fût de vérin ovalisé.",
    causeEn: "Damaged piston seal or cylinder barrel ovalization.",
    causeEs: "Junta de pistón interna dañada o cuerpo del cilindro ovalado.",
    action: "Démonter le vérin, inspecter la chemise, remplacer le joint de piston.",
    actionEn: "Disassemble cylinder, inspect inner bore, replace piston seal.",
    actionEs: "Desmontar cilindro, inspeccionar camisa, reemplazar junta de pistón.",
    repTime: 3.0
  },
  {
    id: "3.3.1.C",
    system: "SYS3",
    title: "Vérin hoist gauche tige rayée",
    titleEn: "Left hoist cylinder rod scratched",
    titleEs: "Vástago de cilindro hoist izquierdo rayado",
    severity: "JAUNE",
    symptoms: "Fuite d'huile persistante sur la tige même après changement de joint.",
    symptomsEn: "Persistent oil leak on rod surface even after installing new seal.",
    symptomsEs: "Fuga persistente en vástago incluso tras instalar junta nueva.",
    cause: "Chute de pierre ou contact abrasif direct sur le chrome dur.",
    causeEn: "Rock fall or direct abrasive contact on the hard chrome rod.",
    causeEs: "Caída de roca o contacto abrasivo directo sobre el cromo duro.",
    action: "Recharger la tige ou la polir, remplacer la tige si rayures profondes.",
    actionEn: "Polishing or re-chroming rod, replace cylinder rod if scratches are deep.",
    actionEs: "Pulir vástago o cambiar vástago si las rayas son profundas.",
    repTime: 3.0
  },
  {
    id: "3.4.1.A",
    system: "SYS3",
    title: "Vérin dump ne sort pas",
    titleEn: "Dump cylinder won't extend",
    titleEs: "Cilindro de volteo no se extiende",
    severity: "ROUGE",
    symptoms: "Godet bloqué en position de déchargement, vérin dump inerte.",
    symptomsEn: "Bucket stuck in dump position, dump cylinder inert.",
    symptomsEs: "Godet bloqueado en posición de descarga, cilindro dump inerte.",
    cause: "Tiroir de distributeur bloqué ou valve de surpression de choc bloquée ouverte.",
    causeEn: "Control valve spool seized or shock-relief valve stuck open.",
    causeEs: "Carrete de válvula de control gripado o válvula de choque abierta.",
    action: "Nettoyer le tiroir du distributeur, inspecter la valve de choc.",
    actionEn: "Clean control spool inside valve slice, inspect shock relief valve.",
    actionEs: "Limpiar carrete del distribuidor, inspeccionar válvula de choque.",
    repTime: 2.0
  },
  {
    id: "3.5.1.A",
    system: "SYS3",
    title: "Vérin godet mouvement saccadé",
    titleEn: "Bucket cylinder movement jerky",
    titleEs: "Cilindro de godet movimiento espasmódico",
    severity: "VERT",
    symptoms: "Le godet tremble ou bouge par saccades lors des manoeuvres légères.",
    symptomsEn: "Bucket vibrates or moves in steps during slight adjustments.",
    symptomsEs: "El cucharón vibra o se mueve a sacudidas en maniobras ligeras.",
    cause: "Présence d'air dans le circuit hydraulique de vérin ou manque de graisse axes.",
    causeEn: "Presence of air in cylinder circuit or dry/unlubricated pins.",
    causeEs: "Presencia de aire en el circuito del cilindro o falta de grasa en ejes.",
    action: "Purger l'air par cycles répétés de butée à butée, graisser les axes.",
    actionEn: "Purge air by cycling cylinder full stroke multiple times, grease pins.",
    actionEs: "Purgar aire con ciclos de carrera completa, engrasar ejes.",
    repTime: 0.8
  },
  {
    id: "3.6.1.A",
    system: "SYS3",
    title: "Refroidisseur hydraulique colmaté",
    titleEn: "Hydraulic oil cooler clogged",
    titleEs: "Enfriador hidráulique obstruido",
    severity: "JAUNE",
    symptoms: "Température d'huile dépasse 80°C rapidement sous effort.",
    symptomsEn: "Hydraulic oil temperature exceeds 80°C quickly under high duty cycle.",
    symptomsEs: "La temperatura del aceite supera 80°C rápido bajo esfuerzo.",
    cause: "Faisceau extérieur bouché par la boue ou calamine interne.",
    causeEn: "External fins clogged with mud/debris or internal carbon buildup.",
    causeEs: "Aletas externas obstruidas por lodo o incrustaciones internas.",
    action: "Laver les ailettes extérieures à basse pression. Détartrer le radiateur.",
    actionEn: "Clean external fins with low-pressure washer. Flush internal tube core.",
    actionEs: "Limpiar aletas exteriores con agua a baja presión. Desincrustar.",
    repTime: 1.5
  },
  {
    id: "3.7.1.A",
    system: "SYS3",
    title: "Pilot pressure insuffisante",
    titleEn: "Insufficient pilot pressure",
    titleEs: "Presión de pilotaje insuficiente",
    severity: "JAUNE",
    symptoms: "Les manettes/joysticks réagissent très mollement ou pas du tout.",
    symptomsEn: "Joysticks respond extremely slowly or do not trigger functions.",
    symptomsEs: "Los joysticks responden muy lentamente o no reaccionan.",
    cause: "Réducteur de pression de pilotage déréglé ou filtre de pilotage bouché.",
    causeEn: "Pilot pressure reducing valve out of spec or pilot filter clogged.",
    causeEs: "Válvula reductora de pilotaje desajustada o filtro obstruido.",
    action: "Mesurer et régler à 3.5 MPa, remplacer le filtre de pilotage.",
    actionEn: "Measure and adjust to 3.5 MPa, replace the pilot oil filter.",
    actionEs: "Medir y ajustar a 3.5 MPa, reemplazar el filtro de pilotaje.",
    repTime: 1.0
  },
  {
    id: "3.8.1.A",
    system: "SYS3",
    title: "By-pass thermostatique bloqué",
    titleEn: "Thermostatic bypass valve stuck",
    titleEs: "Válvula bypass termostática atascada",
    severity: "VERT",
    symptoms: "Huile hydraulique reste très froide en hiver (usure accrue des pompes).",
    symptomsEn: "Hydraulic oil remains too cold in winter (increased pump wear).",
    symptomsEs: "El aceite permanece muy frío en invierno (desgaste de bombas).",
    cause: "Thermostat d'huile bloqué ouvert redirigeant vers le refroidisseur.",
    causeEn: "Oil thermostat stuck open sending cold oil to cooler continuously.",
    causeEs: "Termostato de aceite atascado abierto enviando aceite al enfriador.",
    action: "Vérifier la valve thermostatique, remplacer la cartouche sensible.",
    actionEn: "Check thermostatic valve, replace the temperature-sensitive cartridge.",
    actionEs: "Verificar la válvula termostática, cambiar cartucho térmico.",
    repTime: 0.8
  },
  {
    id: "3.1.3.A",
    system: "SYS3",
    title: "Distributeur principal monostick grippé",
    titleEn: "Main monostick control valve seized",
    titleEs: "Distribuidor principal monostick gripado",
    severity: "ROUGE",
    symptoms: "Mouvement continu d'un vérin (boom ou godet) sans toucher le joystick.",
    symptomsEn: "Continuous uncommanded cylinder movement (boom or bucket) without joystick input.",
    symptomsEs: "Movimiento continuo de un cilindro sin tocar el joystick.",
    cause: "Ressort de rappel de tiroir cassé ou bavure métallique bloquant le tiroir.",
    causeEn: "Broken spool centering spring or metal burr pinning the spool.",
    causeEs: "Resorte de retorno del carrete roto o rebaba metálica que lo bloquea.",
    action: "Déposer l'élément de distributeur, polir le tiroir ou changer l'élément.",
    actionEn: "Remove valve slice, polish spool or replace the valve slice.",
    actionEs: "Desmontar elemento del distribuidor, pulir carrete o cambiarlo.",
    repTime: 3.0
  },
  {
    id: "3.2.3.A",
    system: "SYS3",
    title: "Limiteur pression principal déréglé",
    titleEn: "Main relief valve out of adjustment",
    titleEs: "Limitador de presión principal desajustado",
    severity: "JAUNE",
    symptoms: "Force d'arrachement au godet insuffisante, impossible de lever pleine charge.",
    symptomsEn: "Insufficient bucket breakout force, unable to lift full load.",
    symptomsEs: "Fuerza de excavación del cucharón insuficiente, no levanta carga.",
    cause: "Ressort du limiteur fatigué ou impureté sur le siège du clapet pilote.",
    causeEn: "Tired relief spring or debris on the pilot valve cone seat.",
    causeEs: "Resorte del limitador fatigado o impureza en el asiento de aguja.",
    action: "Vérifier avec manomètre et ajuster à la pression prescrite (13 MPa).",
    actionEn: "Check with pressure gauge and adjust to nominal pressure (13 MPa).",
    actionEs: "Verificar con manómetro y ajustar a presión nominal (13 MPa).",
    repTime: 0.5
  },
  {
    id: "3.3.2.A",
    system: "SYS3",
    title: "Vérin hoist droit désynchronisé",
    titleEn: "Right hoist cylinder desynchronized",
    titleEs: "Cilindro hoist derecho desincronizado",
    severity: "VERT",
    symptoms: "Le boom s'élève de biais, contraintes mécaniques et bruits de torsion.",
    symptomsEn: "Boom raises unevenly, mechanical stress and torsion sounds.",
    symptomsEs: "El boom se eleva torcido, tensión mecánica y ruidos de torsión.",
    cause: "Fuite interne asymétrique ou restriction de passage sur un flexible.",
    causeEn: "Asymmetric internal leak or flow restriction in one hose line.",
    causeEs: "Fuga interna asimétrica o restricción de flujo en una manguera.",
    action: "Purger l'air des deux côtés, mesurer et équilibrer les pressions.",
    actionEn: "Bleed air from both lines, measure and balance hydraulic pressures.",
    actionEs: "Purgar el aire de ambas líneas, medir y equilibrar presiones.",
    repTime: 1.5
  },

  // SYSTEME 4 - DIRECTION & ARTICULATION
  {
    id: "4.1.1.A",
    system: "SYS4",
    title: "Orbitrol grippé",
    titleEn: "Orbitrol steering unit seized",
    titleEs: "Orbitrol de dirección gripado",
    severity: "ROUGE",
    symptoms: "Volant impossible à tourner manuellement, roues avant immobiles.",
    symptomsEn: "Steering wheel impossible to turn, front wheels locked straight.",
    symptomsEs: "Volante imposible de girar, ruedas inmóviles.",
    cause: "Pollution métallique massive du circuit bloquant l'unité rotative.",
    causeEn: "Massive metal debris pollution locking the rotary valve rotor.",
    causeEs: "Contaminación metálica masiva que bloquea el rotor rotativo.",
    action: "Remplacer l'orbitrol de direction et rincer la ligne de direction.",
    actionEn: "Replace orbitrol steering unit and flush steering hydraulic lines.",
    actionEs: "Reemplazar el orbitrol de dirección y lavar líneas de dirección.",
    repTime: 3.5
  },
  {
    id: "4.1.2.A",
    system: "SYS4",
    title: "Vérin direction gauche fuite",
    titleEn: "Left steering cylinder leak",
    titleEs: "Fuga cilindro de dirección izquierdo",
    severity: "JAUNE",
    symptoms: "La machine dérive lentement de trajectoire, fuite d'huile visible au sol.",
    symptomsEn: "Machine drifts slowly, visible hydraulic oil pool on floor.",
    symptomsEs: "La máquina se desvía lentamente, fuga visible de aceite.",
    cause: "Usure accélérée des joints par projection de graviers de mine.",
    causeEn: "Accelerated seal wear due to impact of sharp mine rocks.",
    causeEs: "Desgaste acelerado de juntas por impacto de rocas afiladas.",
    action: "Remplacer le kit de joints d'étanchéité du vérin gauche.",
    actionEn: "Replace the seal kit for the left steering cylinder.",
    actionEs: "Reemplazar el kit de juntas del cilindro izquierdo.",
    repTime: 2.0
  },
  {
    id: "4.2.1.A",
    system: "SYS4",
    title: "Roulement articulation usé",
    titleEn: "Articulation bearing worn",
    titleEs: "Rodamiento de articulación desgastado",
    severity: "JAUNE",
    symptoms: "Jeu vertical ou horizontal au point de pivot lors des virages serrés.",
    symptomsEn: "Vertical or horizontal play at pivot point during tight turns.",
    symptomsEs: "Juego vertical u horizontal en el pivote durante giros cerrados.",
    cause: "Graissage insuffisant ou charge dynamique excessive continue.",
    causeEn: "Insufficient lubrication or continuous heavy dynamic loading.",
    causeEs: "Lubricación insuficiente o carga dinámica pesada continua.",
    action: "Mesurer le jeu axial. Remplacer les roulements pivot d'articulation.",
    actionEn: "Measure axial play. Replace articulation pivot bearings.",
    actionEs: "Medir juego axial. Reemplazar rodamientos de articulación.",
    repTime: 6.0
  },
  {
    id: "4.2.3.A",
    system: "SYS4",
    title: "Joint cardan articulation cassé",
    titleEn: "Articulation cardan joint broken",
    titleEs: "Junta cardán de articulación rota",
    severity: "ROUGE",
    symptoms: "Bruit de choc extrême sous la cabine, la machine s'arrête de suite.",
    symptomsEn: "Extreme impact noise under cabin, machine stops instantly.",
    symptomsEs: "Ruido de impacto extremo bajo cabina, parada instantánea.",
    cause: "Croisillon de cardan usé ignoré ayant éclaté sous couple de poussée.",
    causeEn: "Worn cardan spider ignored until it shattered under torque.",
    causeEs: "Cruceta desgastada ignorada que estalla bajo esfuerzo de torsión.",
    action: "🛑 SÉCURISER L'ENGIN. Remplacer le cardan et l'arbre intermédiaire pivot.",
    actionEn: "🛑 SECURE MACHINE. Replace cardan joint and intermediate pivot shaft.",
    actionEs: "🛑 ASEGURAR MÁQUINA. Reemplazar cardán y eje intermedio de pivote.",
    repTime: 5.0
  },
  {
    id: "4.3.1.A",
    system: "SYS4",
    title: "Direction d'urgence défaillante",
    titleEn: "Emergency steering failure",
    titleEs: "Fallo de dirección de emergencia",
    severity: "ROUGE",
    symptoms: "Direction non assistée lorsque le moteur s'arrête en descente.",
    symptomsEn: "No steering assist when engine shuts down on ramps.",
    symptomsEs: "Sin asistencia de dirección si el motor se apaga en rampa.",
    cause: "Moteur électrique de secours grillé ou électrovanne bloquée.",
    causeEn: "Emergency electric steering motor burnt or solenoid valve seized.",
    causeEs: "Motor eléctrico de emergencia quemado o electroválvula gripada.",
    action: "Tester le relais électrique, changer le moteur de pompe d'urgence.",
    actionEn: "Test electrical relay, replace the emergency steering pump motor.",
    actionEs: "Probar relé eléctrico, reemplazar motor de bomba de emergencia.",
    repTime: 2.0
  },
  {
    id: "4.2.4.A",
    system: "SYS4",
    title: "Boulons articulation desserrés",
    titleEn: "Articulation bolts loose",
    titleEs: "Pernos de articulación flojos",
    severity: "JAUNE",
    symptoms: "Claquements répétitifs lors des virages légers de gauche à droite.",
    symptomsEn: "Repetitive clicking sounds during slight steering corrections.",
    symptomsEs: "Golpeteos repetitivos en ligeras correcciones de dirección.",
    cause: "Absence de vérification du couple de serrage périodique ou vibrations.",
    causeEn: "Lack of periodic torque checks or high vibration running.",
    causeEs: "Falta de control de torque periódico o vibraciones de marcha.",
    action: "Resserrer au couple prescrit, appliquer du frein filet bleu.",
    actionEn: "Retighten to spec, apply blue thread locker fluid.",
    actionEs: "Apretar a torque especificado, aplicar fijador de roscas azul.",
    repTime: 1.0
  },

  // SYSTEME 5 - FREINAGE SAHR
  {
    id: "5.1.1.A",
    system: "SYS5",
    title: "Disques frein usés sous épaisseur min",
    titleEn: "Brake discs worn below min thickness",
    titleEs: "Discos de freno desgastados bajo espesor mín",
    severity: "ROUGE",
    symptoms: "Freinage inefficace en rampe, échauffement anormal de l'essieu.",
    symptomsEn: "Ineffective braking on ramp, abnormal axle temperature rise.",
    symptomsEs: "Frenado ineficaz en rampa, sobrecalentamiento del eje.",
    cause: "Usure normale abrasive des disques humides multilamelles.",
    causeEn: "Normal abrasive wear of the multi-wet disc packs.",
    causeEs: "Desgaste normal abrasivo de discos húmedos multilaminados.",
    action: "Déposer le moyeu d'essieu, mesurer l'épaisseur, remplacer les disques.",
    actionEn: "Disassemble axle hub, measure thickness, replace wet discs.",
    actionEs: "Desmontar cubo de eje, medir espesor, reemplazar discos.",
    repTime: 6.0
  },
  {
    id: "5.1.2.A",
    system: "SYS5",
    title: "Plaquettes SAHR usées",
    titleEn: "SAHR pads worn out",
    titleEs: "Pastillas SAHR desgastadas",
    severity: "JAUNE",
    symptoms: "Course de piston SAHR excessive, temps de réaction de freinage long.",
    symptomsEn: "Excessive SAHR piston stroke, slow brake engagement reaction.",
    symptomsEs: "Carrera de pistón SAHR excesiva, reacción de frenado lenta.",
    cause: "Frictions d'arrêt d'urgence répétées sans ajustement.",
    causeEn: "Repeated emergency brake stops without interval inspection.",
    causeEs: "Frenados de emergencia repetidos sin inspección periódica.",
    action: "Remplacer le jeu de plaquettes de friction SAHR.",
    actionEn: "Replace the SAHR friction pad set.",
    actionEs: "Reemplazar el juego de pastillas de fricción SAHR.",
    repTime: 1.8
  },
  {
    id: "5.1.3.A",
    system: "SYS5",
    title: "Étriers hydrauliques grippés",
    titleEn: "Hydraulic caliper pistons seized",
    titleEs: "Pistones de pinzas hidráulicas gripados",
    severity: "JAUNE",
    symptoms: "La machine tire d'un côté au freinage, fumée sur un étrier.",
    symptomsEn: "Machine pulls to one side during braking, smoke rising from caliper.",
    symptomsEs: "La máquina tira a un lado al frenar, humo en una pinza.",
    cause: "Corrosion due à l'eau de mine saline s'infiltrant sous les joints.",
    causeEn: "Corrosion caused by salty mine water seeping behind boots.",
    causeEs: "Corrosión por agua salada de la mina que penetra tras sellos.",
    action: "Déposer l'étrier, nettoyer le piston, changer les joints d'étanchéité.",
    actionEn: "Remove caliper, clean piston bore, install new seal kit.",
    actionEs: "Desmontar pinza, limpiar pistón, instalar kit de sellos nuevo.",
    repTime: 2.5
  },
  {
    id: "5.2.1.A",
    system: "SYS5",
    title: "Mécanisme parking bloqué",
    titleEn: "Parking mechanism jammed",
    titleEs: "Mecanismo de freno de mano bloqueado",
    severity: "ROUGE",
    symptoms: "La machine refuse d'avancer malgré une pression hydraulique correcte.",
    symptomsEn: "Machine refuses to move despite correct pilot release pressure.",
    symptomsEs: "La máquina no avanza pese a presión de liberación correcta.",
    cause: "Rupture de ressort interne de rappel du bloc SAHR de parking.",
    causeEn: "Broken internal release spring inside SAHR parking canister.",
    causeEs: "Rotura de resorte de liberación interno en cilindro SAHR.",
    action: "Remplacer le cylindre complet du frein de stationnement SAHR.",
    actionEn: "Replace complete SAHR parking brake cylinder canister.",
    actionEs: "Reemplazar el cilindro de freno SAHR completo.",
    repTime: 3.0
  },
  {
    id: "5.3.1.A",
    system: "SYS5",
    title: "Accumulateur vide / perte précharge",
    titleEn: "Accumulator empty / loss of precharge nitrogen",
    titleEs: "Acumulador vacío / pérdida de precarga de nitrógeno",
    severity: "ROUGE",
    symptoms: "Pédale de frein dure comme du bois, seulement 1 ou 2 coups assistés.",
    symptomsEn: "Extremely hard brake pedal, only 1 or 2 power-assisted strokes available.",
    symptomsEs: "Pedal de freno muy duro, solo 1 o 2 frenados asistidos disponibles.",
    cause: "Fuite lente d'azote par la valve de charge ou fissure de membrane.",
    causeEn: "Slow nitrogen gas leak through filling valve or ruptured bladder.",
    causeEs: "Fuga lenta de nitrógeno por válvula de carga o membrana rota.",
    action: "Vérifier la précharge azote, recharger ou remplacer l'accumulateur.",
    actionEn: "Check nitrogen precharge pressure, recharge gas or replace accumulator.",
    actionEs: "Verificar precarga de nitrógeno, recargar gas o cambiar acumulador.",
    repTime: 1.5
  },
  {
    id: "5.3.1.B",
    system: "SYS5",
    title: "Accumulateur fuite interne",
    titleEn: "Accumulator internal leak",
    titleEs: "Fuga interna de acumulador",
    severity: "ROUGE",
    symptoms: "Huile hydraulique mousseuse dans le réservoir de freinage.",
    symptomsEn: "Foamy hydraulic oil visible in the braking circuit reservoir.",
    symptomsEs: "Aceite hidráulico espumoso en depósito del circuito de frenos.",
    cause: "Membrane d'azote poreuse ou percée, azote s'est mélangé à l'huile.",
    causeEn: "Porous or ruptured gas bladder, nitrogen mixed directly with oil.",
    causeEs: "Membrana porosa o rota, mezcla directa de nitrógeno con aceite.",
    action: "Remplacer impérativement l'accumulateur de freinage par un neuf.",
    actionEn: "Replace the brake accumulator immediately with a brand new unit.",
    actionEs: "Reemplazar acumulador de frenos de inmediato por uno nuevo.",
    repTime: 1.5
  },
  {
    id: "5.3.2.A",
    system: "SYS5",
    title: "Pompe charge freinage morte",
    titleEn: "Brake charging pump dead",
    titleEs: "Bomba de carga de frenos dañada",
    severity: "ROUGE",
    symptoms: "Voyant pression freinage rouge reste allumé en continu, pas de release.",
    symptomsEn: "Red brake pressure warning lamp stays on, brakes fail to release.",
    symptomsEs: "Luz de presión de frenos encendida, frenos no liberan.",
    cause: "Casse interne des engrenages de la petite pompe accouplée.",
    causeEn: "Internal gear teeth breakage in the small auxiliary pump section.",
    causeEs: "Rotura de dientes de engranaje interno en sección de bomba auxiliar.",
    action: "Déposer la pompe de charge freinage et installer une neuve.",
    actionEn: "Remove brake charge pump section and install a new assembly.",
    actionEs: "Desmontar sección de bomba de carga de frenos e instalar nueva.",
    repTime: 2.5
  },
  {
    id: "5.3.4.A",
    system: "SYS5",
    title: "Électrovanne release défectueuse",
    titleEn: "Release solenoid valve defective",
    titleEs: "Electroválvula de liberación defectuosa",
    severity: "JAUNE",
    symptoms: "Les freins se relâchent de façon intermittente ou très lente.",
    symptomsEn: "Brakes release intermittently or extremely slowly.",
    symptomsEs: "Los frenos liberan de forma intermitente o muy lenta.",
    cause: "Bobine électrique de l'électrovanne grillée ou tiroir collant à chaud.",
    causeEn: "Solenoid coil burnt out or control spool sticky at high temp.",
    causeEs: "Bobina quemada o carrete de control pegajoso a alta temperatura.",
    action: "Changer la bobine 24V ou remplacer la cartouche de l'électrovanne.",
    actionEn: "Replace the 24V solenoid coil or change the cartridge valve.",
    actionEs: "Reemplazar bobina de 24V o cambiar el cartucho de válvula.",
    repTime: 1.0
  },
  {
    id: "5.3.5.A",
    system: "SYS5",
    title: "Capteur pression accumulateur défectueux",
    titleEn: "Accumulator pressure sensor faulty",
    titleEs: "Sensor de presión de acumulador defectuoso",
    severity: "VERT",
    symptoms: "Alarme pression basse allumée à tort alors que les freins fonctionnent bien.",
    symptomsEn: "Low pressure warning active falsely while brakes operate normally.",
    symptomsEs: "Alarma de baja presión falsa activa mientras frenos andan bien.",
    cause: "Dérive du signal électrique interne ou corrosion de la broche.",
    causeEn: "Sensor signal drift or terminal pin corrosion on connector.",
    causeEs: "Desviación de señal del sensor o corrosión de pines del conector.",
    action: "Nettoyer le connecteur, remplacer le capteur de pression d'huile.",
    actionEn: "Clean electric connector plug, replace the oil pressure sensor.",
    actionEs: "Limpiar enchufe conector, reemplazar sensor de presión de aceite.",
    repTime: 0.8
  },
  {
    id: "5.4.1.A",
    system: "SYS5",
    title: "Neutral brake ne fonctionne pas",
    titleEn: "Neutral brake does not activate",
    titleEs: "Freno de neutro no activa",
    severity: "ROUGE",
    symptoms: "La machine dévale en pente dès que le joystick de marche revient au neutre.",
    symptomsEn: "Machine rolls down slope immediately when travel joystick returns to neutral.",
    symptomsEs: "La máquina rueda en rampa al soltar joystick de marcha al neutro.",
    cause: "Signal électrique de coupure non transmis au bloc de frein d'urgence.",
    causeEn: "Electrical cutoff signal not transmitted to emergency brake block.",
    causeEs: "Señal eléctrica de corte no transmitida al bloque de freno de emergencia.",
    action: "Vérifier le contacteur du joystick et calibrer le signal de neutre de l'ECM.",
    actionEn: "Check joystick microswitch contacts, calibrate ECM neutral signals.",
    actionEs: "Revisar microinterruptor de joystick, calibrar señales de neutro del ECM.",
    repTime: 1.5
  },

  // SYSTEME 6 - ELECTRIQUE
  {
    id: "6.1.1.A",
    system: "SYS6",
    title: "Batterie déchargée",
    titleEn: "Battery discharged",
    titleEs: "Batería descargada",
    severity: "VERT",
    symptoms: "Click-click au démarreur, baisse d'intensité lumineuse au tableau.",
    symptomsEn: "Rapid clicking sounds at starter, dash lights dim severely.",
    symptomsEs: "Sonidos de clic rápido en arranque, luces del tablero se atenúan.",
    cause: "Oubli de phares allumés à l'arrêt ou courant de fuite permanent.",
    causeEn: "Lights left on during shutdown or parasitic current drain.",
    causeEs: "Luces encendidas tras apagar motor o drenaje de corriente parásito.",
    action: "Recharger la batterie, vérifier l'absence de consommateur pirate.",
    actionEn: "Recharge battery set, check for parasitic electrical loads.",
    actionEs: "Recargar juego de baterías, verificar consumos parásitos.",
    repTime: 0.5
  },
  {
    id: "6.1.1.B",
    system: "SYS6",
    title: "Batterie sulfatée",
    titleEn: "Battery sulfated",
    titleEs: "Batería sulfatada",
    severity: "VERT",
    symptoms: "Perte rapide de capacité, ne tient pas la charge au-delà de 12 heures.",
    symptomsEn: "Rapid capacity loss, won't hold charge for more than 12 hours.",
    symptomsEs: "Pérdida rápida de capacidad, no retiene carga más de 12 horas.",
    cause: "Batterie restée déchargée trop longtemps en milieu humide.",
    causeEn: "Battery left deeply discharged for too long in humid environments.",
    causeEs: "Batería descargada por mucho tiempo en ambiente húmedo.",
    action: "Remplacer le bloc batterie complet de 24V (deux batteries de 12V).",
    actionEn: "Replace complete 24V battery set (two 12V blocks in series).",
    actionEs: "Reemplazar juego de baterías de 24V completo (dos de 12V).",
    repTime: 0.5
  },
  {
    id: "6.1.2.A",
    system: "SYS6",
    title: "Démarreur ne tourne pas",
    titleEn: "Starter motor won't turn",
    titleEs: "Motor de arranque no gira",
    severity: "JAUNE",
    symptoms: "Silence total en tournant la clé de contact, batterie pourtant OK.",
    symptomsEn: "Total silence when turning ignition key, battery status is normal.",
    symptomsEs: "Silencio total al girar llave, batería en buen estado.",
    cause: "Solenoid de démarreur HS ou charbons internes totalement usés.",
    causeEn: "Starter solenoid failure or internal carbon brushes completely worn.",
    causeEs: "Solenoides de arranque dañados o escobillas de carbón gastadas.",
    action: "Frapper doucement sur le solénoïde pour tester. Remplacer le démarreur.",
    actionEn: "Tap solenoid gently to test. Replace starter motor assembly.",
    actionEs: "Golpear solenoide suavemente para probar. Reemplazar motor de arranque.",
    repTime: 1.5
  },
  {
    id: "6.1.3.A",
    system: "SYS6",
    title: "Alternateur ne charge pas",
    titleEn: "Alternator not charging",
    titleEs: "Alternador no carga",
    severity: "JAUNE",
    symptoms: "Tension batterie chute sous 23V moteur tournant, voyant batterie allumé.",
    symptomsEn: "Battery voltage drops below 23V with engine running, red battery icon.",
    symptomsEs: "Voltaje baja de 23V con motor encendido, luz de batería.",
    cause: "Régulateur de tension de l'alternateur grillé ou courroie détendue.",
    causeEn: "Burnt voltage regulator in alternator or loose/slipping drive belt.",
    causeEs: "Regulador de voltaje quemado o correa de transmisión floja.",
    action: "Mesurer la tension aux bornes (norme: 27.5V), changer l'alternateur.",
    actionEn: "Check terminal output (normal is 27.5V), replace alternator assembly.",
    actionEs: "Medir salida (normal es 27.5V), reemplazar conjunto del alternador.",
    repTime: 1.2
  },
  {
    id: "6.2.1.A",
    system: "SYS6",
    title: "Tableau de bord noir",
    titleEn: "Dashboard black screen",
    titleEs: "Tablero de instrumentos apagado",
    severity: "JAUNE",
    symptoms: "Aucun indicateur ni écran allumé en position contact clé.",
    symptomsEn: "Zero indicators or display screens active with ignition on.",
    symptomsEs: "Cero indicadores o pantallas activos al dar contacto.",
    cause: "Relais d'alimentation principale du cockpit défectueux ou fusible grillé.",
    causeEn: "Defective main cabin power relay or blown fuse.",
    causeEs: "Relé de potencia de cabina defectuoso o fusible quemado.",
    action: "Vérifier le fusible cabine 15A, remplacer le relais d'alimentation.",
    actionEn: "Check 15A cabin fuse, replace master power supply relay.",
    actionEs: "Revisar fusible de cabina de 15A, reemplazar relé principal.",
    repTime: 1.0
  },
  {
    id: "6.4.1.A",
    system: "SYS6",
    title: "RRC ne s'appaire pas",
    titleEn: "RRC remote control fails to pair",
    titleEs: "El control remoto RRC no empareja",
    severity: "VERT",
    symptoms: "L'émetteur radio clignote rouge, pas de réponse de la machine.",
    symptomsEn: "Radio transmitter flashes red, no machine control response.",
    symptomsEs: "El transmisor de radio parpadea en rojo, sin respuesta de máquina.",
    cause: "Canal radio incorrect ou récepteur RRC de l'engin non alimenté.",
    causeEn: "Incorrect radio frequency channel or unpowered machine RRC receiver.",
    causeEs: "Canal de radio incorrecto o receptor RRC sin energía.",
    action: "Vérifier l'adresse ID, réinitialiser la liaison radio récepteur.",
    actionEn: "Verify ID address code, restart receiver power link to reset.",
    actionEs: "Verificar código ID, reiniciar enlace de radio para restablecer.",
    repTime: 0.8
  },
  {
    id: "6.4.1.B",
    system: "SYS6",
    title: "RRC commande erratique",
    titleEn: "Erratic RRC remote response",
    titleEs: "Respuesta errática del control RRC",
    severity: "JAUNE",
    symptoms: "Mouvements retardés ou saccadés de l'engin via télécommande.",
    symptomsEn: "Delayed or sudden jumps in machine action via remote.",
    symptomsEs: "Movimientos retrasados o bruscos de máquina vía control.",
    cause: "Interférences électromagnétiques locales ou antenne réceptrice cassée.",
    causeEn: "Local electromagnetic interference or broken receiver antenna.",
    causeEs: "Interferencia electromagnética local o antena receptora rota.",
    action: "Inspecter l'antenne extérieure sur l'engin, changer le câble coaxial.",
    actionEn: "Inspect external antenna on machine canopy, replace coaxial cable.",
    actionEs: "Inspeccionar antena exterior en cabina, reemplazar cable coaxial.",
    repTime: 1.0
  },
  {
    id: "6.5.1.A",
    system: "SYS6",
    title: "Alarme recul défectueuse",
    titleEn: "Backup alarm failure",
    titleEs: "Fallo de alarma de retroceso",
    severity: "VERT",
    symptoms: "Aucun signal sonore lors de l'inversion de marche en arrière.",
    symptomsEn: "No acoustic alert sound during reverse gear travel.",
    symptomsEs: "Sin alerta acústica durante la marcha atrás.",
    cause: "Haut-parleur d'alarme grillé ou câble sectionné à l'arrière de l'engin.",
    causeEn: "Burnt alarm speaker horn or severed wire at the rear frame.",
    causeEs: "Bocina de alarma quemada o cable cortado en chasis trasero.",
    action: "Mesurer la tension 24V au connecteur, remplacer l'alarme sonore.",
    actionEn: "Check 24V feed voltage at rear connector, replace backup alarm horn.",
    actionEs: "Medir voltaje de 24V en conector trasero, reemplazar bocina.",
    repTime: 0.5
  },
  {
    id: "6.6.1.A",
    system: "SYS6",
    title: "Fusible CAN bus grillé",
    titleEn: "Blown CAN bus fuse",
    titleEs: "Fusible CAN bus fundido",
    severity: "ROUGE",
    symptoms: "Arrêt complet, erreur de communication réseau globale sur l'écran.",
    symptomsEn: "Sudden shutdown, global network communication fault active on screen.",
    symptomsEs: "Parada repentina, fallo de comunicación de red global en pantalla.",
    cause: "Court-circuit à la masse sur une branche du faisceau électrique.",
    causeEn: "Short circuit to ground on one branch of the wiring harness.",
    causeEs: "Cortocircuito a tierra en una rama del mazo de cables.",
    action: "Isoler la ligne en court-circuit, remplacer le fusible 10A CAN.",
    actionEn: "Isolate short circuit line branch, replace 10A CAN bus fuse.",
    actionEs: "Aislar rama de cortocircuito, reemplazar fusible de 10A CAN.",
    repTime: 2.0
  },
  {
    id: "6.6.1.B",
    system: "SYS6",
    title: "Masse électrique oxydée",
    titleEn: "Oxidized ground connection",
    titleEs: "Conexión de masa oxidada",
    severity: "JAUNE",
    symptoms: "Multiples défauts électriques intermittents et fantômes.",
    symptomsEn: "Multiple erratic, phantom electrical faults active simultaneously.",
    symptomsEs: "Múltiples fallos eléctricos erráticos y fantasmas.",
    cause: "Corrosion du plot de masse principal en contact avec l'acier humide.",
    causeEn: "Corrosion of master ground stud against humid steel frame.",
    causeEs: "Corrosión del perno de masa principal contra chasis húmedo.",
    action: "Démonter le cosses de masse, brosser à blanc, serrer et graisser.",
    actionEn: "Remove ground connectors, wire brush to bare steel, tighten and grease.",
    actionEs: "Retirar terminales de masa, cepillar acero, apretar y engrasar.",
    repTime: 0.8
  },

  // SYSTEME 7 - REFROIDISSEMENT
  {
    id: "7.1.1.A",
    system: "SYS7",
    title: "Radiateur moteur colmaté",
    titleEn: "Engine radiator clogged",
    titleEs: "Radiador de motor obstruido",
    severity: "JAUNE",
    symptoms: "Surchauffe moteur progressive sous charge élevée.",
    symptomsEn: "Engine coolant temperature climbs steadily under heavy loads.",
    symptomsEs: "La temperatura del motor sube de forma constante bajo carga.",
    cause: "Accumulation de poussières de forage collées par l'huile.",
    causeEn: "Accumulation of drill dust bonded by minor oil weeping.",
    causeEs: "Acumulación de polvo adherido por ligeras fugas de aceite.",
    action: "Nettoyer les ailettes du radiateur avec un jet de vapeur.",
    actionEn: "Wash and clear radiator fins with low-pressure steam/water jet.",
    actionEs: "Limpiar aletas del radiador con chorro de vapor o agua tibia.",
    repTime: 1.0
  },
  {
    id: "7.1.2.A",
    system: "SYS7",
    title: "Ventilateur moteur défectueux",
    titleEn: "Engine cooling fan defective",
    titleEs: "Ventilador de motor defectuoso",
    severity: "ROUGE",
    symptoms: "Surchauffe rapide même moteur au ralenti stationnaire.",
    symptomsEn: "Engine overheats rapidly even at idle speed.",
    symptomsEs: "El motor se sobrecalienta rápidamente incluso en ralentí.",
    cause: "Moteur hydraulique du ventilateur cassé ou courroie rompue.",
    causeEn: "Cooling fan hydraulic motor failed or drive belt broken.",
    causeEs: "Motor hidráulico de ventilador dañado o correa rota.",
    action: "Vérifier le clapet d'alimentation du moteur ou remplacer la courroie.",
    actionEn: "Check motor flow solenoid valve, or replace drive belt.",
    actionEs: "Verificar válvula del motor, o reemplazar correa de transmisión.",
    repTime: 1.5
  },
  {
    id: "7.2.1.A",
    system: "SYS7",
    title: "Refroidisseur hydraulique fuite",
    titleEn: "Hydraulic cooler oil leak",
    titleEs: "Fuga de enfriador de aceite hidráulico",
    severity: "JAUNE",
    symptoms: "Baisse progressive du niveau hydraulique, traînées d'huile.",
    symptomsEn: "Progressive drop of hydraulic oil level, oil tracks on cooler.",
    symptomsEs: "Descenso de nivel hidráulico, trazas de aceite en radiador.",
    cause: "Fissure de fatigue mécanique due aux vibrations sur les soudures.",
    causeEn: "Mechanical fatigue cracks on core welds caused by frame vibrations.",
    causeEs: "Fisuras por fatiga mecánica en soldaduras por vibración.",
    action: "Déposer le refroidisseur pour brasage spécial ou le remplacer.",
    actionEn: "Remove cooler for specialty welding repair or replace unit.",
    actionEs: "Desmontar enfriador para soldadura especial o reemplazar.",
    repTime: 2.0
  },
  {
    id: "7.1.3.A",
    system: "SYS7",
    title: "Thermostat eau défectueux",
    titleEn: "Water thermostat failure",
    titleEs: "Fallo de termostato de agua",
    severity: "JAUNE",
    symptoms: "Indicateur de température d'eau variable de façon erratique.",
    symptomsEn: "Engine temperature fluctuates erratically during hauling.",
    symptomsEs: "La temperatura fluctúa de forma errática durante el transporte.",
    cause: "Usure de l'élément dilatable ou ressort décalibré.",
    causeEn: "Worn wax capsule or return spring decalibrated.",
    causeEs: "Cápsula térmica gastada o resorte descalibrado.",
    action: "Démonter et tester dans l'eau chaude, remplacer la cartouche.",
    actionEn: "Disassemble and test thermostat in boiling water, replace cartridge.",
    actionEs: "Desmontar y probar en agua caliente, reemplazar cartucho.",
    repTime: 1.2
  },

  // SYSTEME 8 - ECHAPPEMENT & VENTILATION
  {
    id: "8.1.1.A",
    system: "SYS8",
    title: "Silencieux percé/fissuré",
    titleEn: "Muffler ruptured/cracked",
    titleEs: "Silenciador roto/fisurado",
    severity: "ROUGE",
    symptoms: "Niveau sonore insupportable en cabine, fumée visible sous le châssis.",
    symptomsEn: "Unbearable noise level in cabin, exhaust gas visible under frame.",
    symptomsEs: "Nivel de ruido insoportable en cabina, humo bajo chasis.",
    cause: "Corrosion acide par condensation d'échappement ou chocs.",
    causeEn: "Acidic corrosion from condensation or mechanical rock strikes.",
    causeEs: "Corrosión ácida por condensación o impactos de rocas.",
    action: "Remplacer le pot d'échappement ou ressouder la section fissurée.",
    actionEn: "Replace the exhaust muffler assembly or weld the cracked section.",
    actionEs: "Reemplazar el silenciador o soldar la sección fisurada.",
    repTime: 2.0
  },
  {
    id: "8.2.1.A",
    system: "SYS8",
    title: "DPF colmaté",
    titleEn: "DPF clogged",
    titleEs: "Filtro DPF obstruido",
    severity: "JAUNE",
    symptoms: "Baisse de puissance moteur flagrante, voyant DPF orange clignote.",
    symptomsEn: "Drastic engine power loss, amber DPF warning lamp flashing.",
    symptomsEs: "Pérdida drástica de potencia, luz DPF parpadea en naranja.",
    cause: "Ralentis prolongés empêchant la régénération naturelle du filtre.",
    causeEn: "Excessive engine idling preventing natural passive soot burn-off.",
    causeEs: "Ralentí prolongado que impide la regeneración pasiva del filtro.",
    action: "Lancer une régénération stationnaire forcée via l'ordinateur de bord.",
    actionEn: "Trigger a forced stationary regeneration cycle using dashboard menu.",
    actionEs: "Iniciar regeneración estacionaria forzada vía menú del tablero.",
    repTime: 1.5
  },
  {
    id: "8.2.1.B",
    system: "SYS8",
    title: "Capteur pression différentielle DPF défectueux",
    titleEn: "DPF differential pressure sensor faulty",
    titleEs: "Sensor de presión diferencial DPF defectuoso",
    severity: "VERT",
    symptoms: "Voyant moteur allumé à tort, régénération DPF impossible.",
    symptomsEn: "Malfunction indicator active falsely, DPF regeneration blocked.",
    symptomsEs: "Luz de motor encendida falsa, regeneración DPF bloqueada.",
    cause: "Accumulation de condensat acide dans les tubes du capteur.",
    causeEn: "Acidic condensate accumulation inside sensor sensing tubes.",
    causeEs: "Acumulación de condensado ácido dentro de los tubos del sensor.",
    action: "Nettoyer les tubes d'échantillonnage, remplacer le capteur de pression.",
    actionEn: "Clean the pressure sampling lines, replace the pressure sensor.",
    actionEs: "Limpiar líneas de muestreo, reemplazar sensor de presión.",
    repTime: 1.0
  },
  {
    id: "8.3.1.A",
    system: "SYS8",
    title: "Surchauffe par manque ventilation chantier",
    titleEn: "Overheating due to lack of gallery ventilation",
    titleEs: "Sobrecalentamiento por falta de ventilación en galería",
    severity: "JAUNE",
    symptoms: "Température moteur monte en flèche seulement au fond du chantier.",
    symptomsEn: "Engine temperature spikes only when operating at face of gallery.",
    symptomsEs: "La temperatura sube de golpe solo al operar al fondo de galería.",
    cause: "Débit d'air frais insuffisant dans la galerie, sous 128 m³/min.",
    causeEn: "Insufficient fresh air flow rate in gallery, below 128 m³/min.",
    causeEs: "Caudal de aire fresco insuficiente en galería, bajo 128 m³/min.",
    action: "Déplacer la machine vers zone aérée, vérifier les manches de ventilation.",
    actionEn: "Move machine to ventilated area, inspect secondary fans & ducting.",
    actionEs: "Mover máquina a zona ventilada, revisar mangas de ventilación.",
    repTime: 0.1
  },

  // SYSTEME 9 - CHASSIS & ROUES
  {
    id: "9.2.1.A",
    system: "SYS9",
    title: "Pneu avant éclaté/déjanté",
    titleEn: "Front tire blowout / bead unseated",
    titleEs: "Neumático delantero reventado / destalonado",
    severity: "ROUGE",
    symptoms: "La machine penche de biais brutalement, bruit fort de décompression.",
    symptomsEn: "Machine tilts suddenly, loud decompression sound.",
    symptomsEs: "La máquina se inclina bruscamente, fuerte ruido de escape de aire.",
    cause: "Pénétration de roche tranchante à forte vitesse sur flanc.",
    causeEn: "Sharp rock puncture on sidewall during high-speed travel.",
    causeEs: "Perforación por roca afilada en flanco a alta velocidad.",
    action: "Remplacer la roue complète par la roue de secours. Réparer le flanc.",
    actionEn: "Replace complete wheel assembly with spare. Repair sidewall in shop.",
    actionEs: "Reemplazar rueda completa por la de repuesto. Reparar flanco.",
    repTime: 1.5
  },
  {
    id: "9.2.1.B",
    system: "SYS9",
    title: "Pression pneus insuffisante",
    titleEn: "Low tire pressure",
    titleEs: "Presión de neumáticos baja",
    severity: "JAUNE",
    symptoms: "Fléchissement visible du flanc du pneu, échauffement anormal de la gomme.",
    symptomsEn: "Visible tire sidewall sagging, abnormal tread temperature rise.",
    symptomsEs: "Deformación visible de flanco, calentamiento del neumático.",
    cause: "Micro-fuite au niveau de la valve de gonflage ou perforation légère.",
    causeEn: "Micro-leak at inflation valve or minor tire puncture.",
    causeEs: "Microfuga en la válvula de inflado o pinchazo menor.",
    action: "Vérifier la pression (norme prescrite), gonfler et changer la valve.",
    actionEn: "Verify pressure (nominal spec), inflate and replace valve core.",
    actionEs: "Verificar presión (especificación), inflar y cambiar obús.",
    repTime: 0.4
  },
  {
    id: "9.2.3.A",
    system: "SYS9",
    title: "Boulons roues desserrés",
    titleEn: "Wheel nuts loose",
    titleEs: "Tuercas de rueda flojas",
    severity: "ROUGE",
    symptoms: "Bruit de claquement lourd à chaque tour de roue, jeu sur jante.",
    symptomsEn: "Heavy knocking sound with every wheel rotation, rim play visible.",
    symptomsEs: "Golpeteo pesado con cada giro de rueda, juego de llanta visible.",
    cause: "Oubli de serrage après changement de roue ou rupture de goujon.",
    causeEn: "Serration skipped after wheel change or wheel stud failure.",
    causeEs: "Falta de apriete tras cambio de rueda o fallo de espárrago.",
    action: "🛑 SÉCURISER L'ENGIN. Serrer en séquence croisée au couple nominal.",
    actionEn: "🛑 SECURE MACHINE. Tighten in star pattern sequence to nominal torque.",
    actionEs: "🛑 ASEGURAR MÁQUINA. Apretar en cruz a torque especificado.",
    repTime: 0.5
  },
  {
    id: "9.3.1.A",
    system: "SYS9",
    title: "Structure ROPS/FOPS fissurée",
    titleEn: "ROPS/FOPS structure cracked",
    titleEs: "Estructura ROPS/FOPS fisurada",
    severity: "ROUGE",
    symptoms: "Fissure apparente sur un des montants principaux de l'arceau cabine.",
    symptomsEn: "Visible crack on one main upright pillar of the cabin canopy.",
    symptomsEs: "Fisura visible en un pilar principal de la cabina de protección.",
    cause: "Fatigue des soudures suite aux vibrations de mine ou impact de roche lourd.",
    causeEn: "Weld fatigue from heavy mine vibrations or severe rock fall impact.",
    causeEs: "Fatiga de soldadura por vibraciones o impacto de roca pesado.",
    action: "🛑 ARRÊT ENGIN. Faire effectuer une soudure certifiée de structure ROPS.",
    actionEn: "🛑 STOP MACHINE. Perform certified welding repair for ROPS cabin safety.",
    actionEs: "🛑 PARADA DE MÁQUINA. Realizar soldadura certificada de ROPS.",
    repTime: 3.0
  },
  {
    id: "9.4.1.A",
    system: "SYS9",
    title: "Silentblocs moteur cassés",
    titleEn: "Broken engine mounts",
    titleEs: "Soportes de motor rotos",
    severity: "JAUNE",
    symptoms: "Bruit de choc métallique intense à l'accélération et à l'arrêt moteur.",
    symptomsEn: "Severe metal impact sound on acceleration and engine shutdown.",
    symptomsEs: "Fuerte golpe metálico al acelerar y al apagar el motor.",
    cause: "Vieillissement de l'élastomère ou surcharge mécanique violente.",
    causeEn: "Elastomer rubber aging or severe torque overload shock.",
    causeEs: "Envejecimiento del elastómero o sobrecarga mecánica violenta.",
    action: "Lever le moteur, démonter et remplacer les silentblocs détériorés.",
    actionEn: "Jack up engine slightly, remove and replace the damaged rubber mounts.",
    actionEs: "Elevar motor levemente, retirar y cambiar soportes dañados.",
    repTime: 4.0
  },

  // SYSTEME 10 - GODET, BOOM & GRAISSAGE
  {
    id: "10.1.1.A",
    system: "SYS10",
    title: "Dents godet cassées/usées",
    titleEn: "Bucket teeth broken/worn out",
    titleEs: "Dientes de cucharón rotos/gastados",
    severity: "VERT",
    symptoms: "Pénétration difficile dans le tas de minerai, temps de cycle de charge long.",
    symptomsEn: "Poor penetration into muckpile, long loading cycle times.",
    symptomsEs: "Dificultad para penetrar mineral, ciclos de carga más lentos.",
    cause: "Abrasion extrême sur roches dures de mine siliceuses.",
    causeEn: "Extreme abrasion against hard siliceous mine rocks.",
    causeEs: "Abrasión extrema contra rocas silíceas duras.",
    action: "Remplacer les dents de godet soudées ou à clavette.",
    actionEn: "Replace welded or pinned bucket shroud/teeth adapters.",
    actionEs: "Reemplazar dientes de cucharón soldados o con pasador.",
    repTime: 2.0
  },
  {
    id: "10.1.3.A",
    system: "SYS10",
    title: "Axe godet ovalisé",
    titleEn: "Bucket pivot pin ovalized",
    titleEs: "Eje de cucharón ovalado",
    severity: "JAUNE",
    symptoms: "Jeu mécanique important au basculement du godet, grincements rudes.",
    symptomsEn: "Significant mechanical play during bucket tilt, harsh squeals.",
    symptomsEs: "Juego mecánico importante al inclinar cucharón, chirridos.",
    cause: "Manque chronique de graissage ou usure par friction directe.",
    causeEn: "Chronic lack of grease lubrication causing direct steel-on-steel friction.",
    causeEs: "Falta crónica de engrase que provoca fricción acero contra acero.",
    action: "Remplacer l'axe de godet et installer des bushings neufs.",
    actionEn: "Replace the bucket pivot pin and install brand new bushings.",
    actionEs: "Reemplazar el eje de cucharón e instalar bujes nuevos.",
    repTime: 3.5
  },
  {
    id: "10.2.1.A",
    system: "SYS10",
    title: "Structure boom fissurée",
    titleEn: "Boom structure cracked",
    titleEs: "Estructura del boom fisurada",
    severity: "ROUGE",
    symptoms: "Fissures visibles sur les bras de levage, surtout près des pivots.",
    symptomsEn: "Visible cracks on lifting arms, especially near pivot bosses.",
    symptomsEs: "Fisuras visibles en brazos de elevación, cerca de pivotes.",
    cause: "Chocs mécaniques répétés contre le front de taille ou surcharge.",
    causeEn: "Repeated mechanical impacts against rock face or heavy overloads.",
    causeEs: "Impactos mecánicos repetidos contra el frente de roca o sobrecarga.",
    action: "🛑 ARRÊT DE L'ENGIN. Réparer par soudage avec chanfreinage certifié.",
    actionEn: "🛑 STOP MACHINE. Grind, preheat and weld crack with certified tech.",
    actionEs: "🛑 PARADA DE MÁQUINA. Amolar, precalentar y soldar fisura.",
    repTime: 5.0
  },
  {
    id: "10.3.1.A",
    system: "SYS10",
    title: "Pompe graissage auto morte",
    titleEn: "Auto lube pump failed",
    titleEs: "Bomba de engrase automático dañada",
    severity: "JAUNE",
    symptoms: "Absence de traces de graisse fraîche sur les articulations de boom.",
    symptomsEn: "No fresh grease traces visible on active boom joints.",
    symptomsEs: "Sin trazas de grasa fresca en articulaciones del boom.",
    cause: "Moteur électrique de pompe grillé ou obstruction solide du réservoir.",
    causeEn: "Electric grease pump motor burnt or solid debris clogging reservoir exit.",
    causeEs: "Motor eléctrico quemado o residuos sólidos que bloquean depósito.",
    action: "Vérifier le fusible de pompe, nettoyer le circuit, remplacer la pompe.",
    actionEn: "Check auto-lube pump fuse, clean grease line paths, replace pump.",
    actionEs: "Revisar fusible de bomba, limpiar líneas de grasa, cambiar bomba.",
    repTime: 1.5
  },
  {
    id: "10.3.1.B",
    system: "SYS10",
    title: "Conduite graissage bouchée",
    titleEn: "Grease line blocked",
    titleEs: "Línea de engrase obstruida",
    severity: "VERT",
    symptoms: "Un ou deux axes restent secs alors que le reste est bien graissé.",
    symptomsEn: "One or two pivot pins remain dry while the rest are lubricated.",
    symptomsEs: "Uno o dos ejes permanecen secos mientras el resto se lubrica.",
    cause: "Graisse séchée durcie obstruant le conduit ou flexible pincé.",
    causeEn: "Hardened dry grease clogging line or pinched grease tube.",
    causeEs: "Grasa seca endurecida obstruyendo conducto o tubo pellizcado.",
    action: "Démonter le tuyau, injecter du solvant ou remplacer le flexible.",
    actionEn: "Disconnect line, flush with solvent or replace grease hose.",
    actionEs: "Desconectar línea, limpiar con solvente o cambiar manguera.",
    repTime: 0.8
  },
  {
    id: "10.3.2.A",
    system: "SYS10",
    title: "Distributeur graissage bloqué",
    titleEn: "Auto-lube progressive divider block jammed",
    titleEs: "Bloque distribuidor progresivo de grasa trabado",
    severity: "JAUNE",
    symptoms: "La pompe auto-lube tourne mais se met en alarme surpression.",
    symptomsEn: "Auto-lube pump cycles but trips immediately on high pressure.",
    symptomsEs: "La bomba de engrase gira pero da alarma de alta presión.",
    cause: "Piston doseur bloqué par une impureté dans le répartiteur.",
    causeEn: "Metering piston jammed by dust particle inside divider valve.",
    causeEs: "Pistón dosificador trabado por partícula dentro de válvula divididora.",
    action: "Démonter le répartiteur progressif, nettoyer les pistons à l'alcool.",
    actionEn: "Disassemble progressive divider block, clean inner spools with alcohol.",
    actionEs: "Desmontar bloque divisor, limpiar pistones con alcohol.",
    repTime: 1.2
  },

  // SYSTEME 11 - SECURITE & ANSUL
  {
    id: "11.1.2.A",
    system: "SYS11",
    title: "Cales roues manquantes",
    titleEn: "Wheel chocks missing",
    titleEs: "Cuñas de rueda faltantes",
    severity: "VERT",
    symptoms: "Pas de cales à bord de l'engin pour immobilisation en pente.",
    symptomsEn: "No heavy rubber wheel chocks on board for slope parking safety.",
    symptomsEs: "Sin cuñas de rueda a bordo para paradas seguras en rampa.",
    cause: "Oubliées sur chantier par l'opérateur lors du dernier arrêt.",
    causeEn: "Left behind in tunnel by operator during previous shift.",
    causeEs: "Olvidadas en galería por el operador en el turno anterior.",
    action: "Fournir immédiatement deux cales réglementaires à stocker sur l'engin.",
    actionEn: "Provide two regulatory chocks to be secured in cabin holder.",
    actionEs: "Proveer dos cuñas reglamentarias para almacenar en cabina.",
    repTime: 0.1
  },
  {
    id: "11.2.1.A",
    system: "SYS11",
    title: "Bouteille Ansul vide",
    titleEn: "Ansul fire bottle empty",
    titleEs: "Botella extintora Ansul vacía",
    severity: "ROUGE",
    symptoms: "Manomètre Ansul dans le rouge, goupille de percussion absente.",
    symptomsEn: "Ansul pressure gauge in red zone, actuator pin is missing.",
    symptomsEs: "Manómetro Ansul en zona roja, falta pasador del actuador.",
    cause: "Déclenchement antérieur non consigné ou fuite lente de pression.",
    causeEn: "Unreported fire discharge event or slow system pressure leak.",
    causeEs: "Activación previa no registrada o fuga lenta de presión.",
    action: "🛑 INTERDICTION DE METTRE EN MARCHE. Recharger et certifier le système Ansul.",
    actionEn: "🛑 NO START ALLOWED. Refill fire tank and re-certify Ansul system.",
    actionEs: "🛑 PROHIBIDO OPERAR. Recargar tanque de extintor y certificar Ansul.",
    repTime: 1.0
  },
  {
    id: "11.2.2.A",
    system: "SYS11",
    title: "Détecteur Ansul défectueux",
    titleEn: "Ansul fire detection sensor faulty",
    titleEs: "Sensor de detección de incendios Ansul defectuoso",
    severity: "JAUNE",
    symptoms: "Voyant d'anomalie système anti-incendie Ansul clignote.",
    symptomsEn: "Ansul fire suppression fault light flashing on steering dash.",
    symptomsEs: "Luz de fallo del sistema contra incendios Ansul parpadea.",
    cause: "Capteur thermique linéaire d'enceinte moteur endommagé.",
    causeEn: "Damaged linear thermal detection wire inside engine shroud.",
    causeEs: "Cable de detección térmica lineal dañado en cárter de motor.",
    action: "Vérifier la boucle de détection linéaire, changer le capteur d'alarme.",
    actionEn: "Verify detection loop electrical continuity, replace fault sensor.",
    actionEs: "Verificar continuidad de lazo, reemplazar sensor de fallo.",
    repTime: 1.2
  },
  {
    id: "11.3.1.A",
    system: "SYS11",
    title: "Boom Up Lock ne verrouille pas",
    titleEn: "Boom Up Lock fails to engage",
    titleEs: "El bloqueo de boom no engancha",
    severity: "ROUGE",
    symptoms: "La goupille de sécurité de boom levé ne rentre pas dans son logement.",
    symptomsEn: "Safety lock bar fails to slide into boom hole when raised.",
    symptomsEs: "Pasador de seguridad de boom elevado no entra en alojamiento.",
    cause: "Déformation mécanique du support de verrou ou dépôt de roche.",
    causeEn: "Mechanical deformation of safety link lock or hard rock debris packing.",
    causeEs: "Deformación mecánica del soporte o acumulación de rocas duras.",
    action: "Nettoyer, détordre le support de goupille ou rectifier l'alignement.",
    actionEn: "Clean, straighten lock bar bracket, adjust raised alignment.",
    actionEs: "Limpiar, enderezar soporte de pasador, ajustar alineamiento.",
    repTime: 1.0
  },
  {
    id: "11.3.2.A",
    system: "SYS11",
    title: "Alarme recul ne fonctionne pas",
    titleEn: "Reverse alarm silent",
    titleEs: "Alarma de marcha atrás silenciosa",
    severity: "JAUNE",
    symptoms: "Voyant d'alarme recul activé mais aucun son émis lors du recul.",
    symptomsEn: "Backup indicator active but no sound emitted during reverse.",
    symptomsEs: "Indicador activo pero sin sonido durante la marcha atrás.",
    cause: "Câble d'alimentation de la sirène sectionné par projection rocheuse.",
    causeEn: "Backup siren power wire cut by sharp rock projection.",
    causeEs: "Cable de alimentación de bocina cortado por proyección de roca.",
    action: "Réparer la liaison électrique du faisceau arrière ou changer la sirène.",
    actionEn: "Repair electric wiring of the rear harness or replace siren.",
    actionEs: "Reparar cableado eléctrico trasero o reemplazar bocina.",
    repTime: 0.8
  }
];

export const EPIROC_ERRORS = [
  { id: 1, text: "Déconnecter la batterie avant l'ECM — Risque élevé de grillage de l'ordinateur Cummins." },
  { id: 2, text: "Démonter le vérin de levage (hoist) sous charge sans caler le boom — Chute mortelle du boom." },
  { id: 3, text: "Oublier de purger l'air après repose d'un vérin hydraulique — Fonctionnement saccadé dangereux." },
  { id: 4, text: "Réutiliser un joint torique hydraulique usagé — Fuite garantie dans les 24 heures de roulage." },
  { id: 5, text: "Serrer les boulons de roues sans séquence croisée en étoile — Voilement immédiat de la jante." },
  { id: 6, text: "Ne pas vérifier la précharge en azote de l'accumulateur — Risque de choc violent interne et de rupture." },
  { id: 7, text: "Remplacer un seul disque de frein sur l'essieu — Déséquilibre sévère de freinage et embardée." },
  { id: 8, text: "Mélanger différentes huiles hydrauliques incompatibles — Formation de boues destructrices." },
  { id: 9, text: "Ignorer l'alignement de l'arbre intermédiaire de transmission — Destruction des cardans en 50h." },
  { id: 10, text: "Oublier la procédure LOTO obligatoire — Démarrage accidentel pendant que le mécanicien travaille." },
  { id: 11, text: "Remplacer les filtres carburant sans pré-amorçage manuel — Introduction d'air fatale pour la rampe HP." },
  { id: 12, text: "Serrer à sec les vis des sections hydrauliques du distributeur — Fissure du carter en fonte." },
  { id: 13, text: "Inverser le sens de circulation des électro-distributeurs — Inversion immédiate des fonctions de cabine." },
  { id: 14, text: "Installer un capteur de pression neuf sans vérifier son câblage — Capteur détruit au premier contact." },
  { id: 15, text: "Ignorer un voyant jaune check engine — Panne majeure critique en gestation rapide au fond." }
];

export const EPIROC_STOCK = {
  "joint-hydraulique": { qty: 2, desc: "Kit joints toriques hydrauliques (raccords et distributeurs)" },
  "soupape-distri": { qty: 2, desc: "Soupape de distribution pilote (direction/travail)" },
  "guidage-piston": { qty: 2, desc: "Bague de guidage piston de vérin hoist/dump" },
  "bushing-godet": { qty: 2, desc: "Bushing en bronze trempé pour pivot de godet" },
  "retainers": { qty: 4, desc: "Axes de retenue de cales et verrouillages" },
  "joints-section": { qty: 4, desc: "Joints d'étanchéité inter-sections de distributeur" },
  "graisse-auto": { qty: 5, desc: "Cartouches de graisse NLGI 2 lithium complexe" },
  "boulon-section": { qty: 1, desc: "Jeu de boulons spéciaux de section de distributeur" },
  "raccords-rapides": { qty: 2, desc: "Raccords hydrauliques rapides face plate" },
  "accumulateur-frein": { qty: 1, desc: "Accumulateur à membrane de freinage SAHR" },
  "plaquettes-sahr": { qty: 2, desc: "Jeux complets de plaquettes d'étriers SAHR" },
  "disques-frein": { qty: 2, desc: "Disques de frein humides multilamelles d'essieu" },
  "filtre-huile": { qty: 4, desc: "Filtres à huile moteur Cummins QSB 4.5" },
  "filtre-carb": { qty: 2, desc: "Filtres carburant primaires + secondaires" },
  "filtre-retour": { qty: 4, desc: "Cartouches de filtre hydraulique de retour" },
  "filtre-pression": { qty: 2, desc: "Filtres hydrauliques haute pression de gavage" },
  "capteur-pression-huile": { qty: 1, desc: "Capteur électrique SPN 100 pression d'huile" },
  "electrovanne-release": { qty: 1, desc: "Électrovanne 24V de release des freins de parking" }
};

export const EPIROC_CONSUMABLES = [
  { product: "Huile moteur", spec: "Cummins CES 20081, 15W-40", ref: "Epiroc 1234-5678", alt: "Shell Rimula R4X 15W-40" },
  { product: "Huile hydraulique", spec: "ISO VG 46, anti-usure", ref: "Epiroc 8765-4321", alt: "Shell Tellus S2 MX 46" },
  { product: "Graisse auto", spec: "NLGI 2, lithium complexe", ref: "Epiroc 1111-2222", alt: "Mobil XHP 222" },
  { product: "Liquide de refroidissement", spec: "ELC (Extended Life Coolant)", ref: "Epiroc 3333-4444", alt: "Fleetguard CC2828" }
];

export const EPIROC_PROCEDURES = [
  { id: "A", title: "LOTO complet ST2G", steps: ["Arrêter moteur, retirer clé", "Couper coupe-circuit principal (+ et -)", "Dépressuriser le réservoir hydraulique", "Dépressuriser les accumulateurs de frein SAHR", "Placer les cales de roues", "Abaisser et verrouiller mécaniquement le boom", "Poser le godet à plat au sol", "Placer le cadenas et le panneau 'NE PAS DÉMARRER'", "Conserver la clé de consignation sur soi"] },
  { id: "B", title: "Dépose vérin hoist", steps: ["Réaliser le LOTO complet", "Caler solidement le bras de levage (boom) en hauteur", "Purger la pression résiduelle de la ligne", "Débrancher les raccords de flexibles, boucher les orifices", "Soutenir le vérin avec une sangle certifiée", "Chasser les axes de pied et de tête de vérin", "Déposer le vérin à l'atelier pour réparation"] },
  { id: "C", title: "Remplacement disques/plaquettes SAHR", steps: ["Immobiliser l'engin à plat", "Dépressuriser totalement le circuit de release", "Déposer la roue concernée", "Démonter l'étrier de frein SAHR", "Retirer les plaquettes de friction usées", "Vérifier l'épaisseur des disques (limite min)", "Installer les plaquettes et disques neufs", "Remonter l'étrier et purger le circuit d'air"] },
  { id: "D", title: "Remplacement accumulateur frein", steps: ["Exécuter la dépressurisation totale du circuit", "Dévisser lentement l'accumulateur défectueux", "Vérifier la pression de précharge d'azote du nouvel accu", "Lubrifier le joint de raccordement", "Visser et serrer l'accumulateur au couple (80 Nm)", "Mettre en pression et tester l'absence de fuites"] },
  { id: "E", title: "Démontage pompe hydrostatique", steps: ["Mettre en place le LOTO", "Vidanger partiellement le réservoir hydraulique", "Débrancher les tuyauteries d'aspiration, de refoulement et de gavage", "Déposer les vis de fixation de la pompe sur le carter d'accouplement", "Extraire la pompe avec précaution", "Inspecter les cannelures de l'arbre d'entraînement"] },
  { id: "F", title: "Remplacement filtre hydraulique", steps: ["Nettoyer le pourtour du boîtier de filtre", "Dévisser la cloche ou la cartouche usagée", "Humidifier le joint torique neuf avec de l'huile propre", "Visser à la main jusqu'au contact, puis serrer de 3/4 de tour", "Démarrer le moteur au ralenti pour purger l'air", "Vérifier le niveau d'huile"] },
  { id: "G", title: "Remplacement filtre carburant", steps: ["Vidanger l'eau présente dans le séparateur", "Remplacer la cartouche primaire et secondaire", "Ne pas remplir les filtres neufs de gasoil brut (risque de pollution)", "Utiliser la pompe d'amorçage manuelle jusqu'à ce qu'elle devienne dure", "Actionner le démarreur sans forcer si de l'air persiste"] },
  { id: "H", title: "Remplacement turbo", steps: ["Laisser refroidir le moteur complètement", "Déposer les conduits d'admission et d'échappement", "Débrancher les conduites d'alimentation et de retour d'huile du turbo", "Dévisser les écrous de collecteur", "Poser le turbo neuf avec des joints métalliques neufs", "Remplir l'orifice de lubrification du turbo d'huile propre avant démarrage"] },
  { id: "I", title: "Révision articulation", steps: ["Séparer mécaniquement le châssis avant et arrière après blocage", "Extraire les axes pivot d'articulation", "Remplacer les roulements coniques pivot", "Ajuster la cale d'épaisseur axiale", "Serrer les vis au couple prescrit, connecter le graissage auto"] },
  { id: "J", title: "Réglage tension chaînes", steps: ["Lever la roue concernée hors-sol", "Dévisser les boulons de blocage du moyeu coulissant", "Actionner la vis de tension pour obtenir une flèche de chaîne de 15 mm", "Serrer les vis de blocage au couple requis", "Vérifier le niveau d'huile dans le carter de chaîne"] },
  { id: "K", title: "Mise en service post-révision", steps: ["Retirer tous les cadenas de consignation LOTO", "Contrôler tous les niveaux de fluides (huile, eau, gasoil)", "Démarrer et laisser tourner au ralenti 5 minutes", "Effectuer des mouvements de vérins à vide à basse vitesse", "Mesurer les pressions de gavage, de travail et de freinage", "Signer la fiche de validation technique"] }
];

export const EPIROC_URGENCES = [
  { id: "13.1", title: "Incendie moteur", text: "Arrêter immédiatement l'engin, couper le contact, percuter l'actionneur Ansul cabine ou moteur, évacuer par le côté opposé aux flammes et appeler le poste central de secours de la mine." },
  { id: "13.2", title: "Freins bloqués en descente", text: "Ne pas paniquer. Utiliser la décélération hydrostatique, appliquer le frein d'urgence manuel. Si impossible, caler l'engin contre le parement (mur) de la galerie de mine pour freiner la dérive." },
  { id: "13.3", title: "Rupture flexible sous pression", text: "🛑 Ne jamais tenter de boucher une fuite avec la main (risque mortel de gangrène par injection sous-cutanée). Arrêter immédiatement le moteur thermique et dépressuriser le réservoir." },
  { id: "13.4", title: "Perte de direction en marche", text: "Relâcher instantanément le joystick de translation pour appliquer le freinage de neutre (neutral brake) et actionner l'interrupteur de la direction électrique d'urgence." },
  { id: "13.5", title: "Fuite carburant majeure", text: "Arrêter le moteur thermique de suite pour éviter le contact du diesel avec le collecteur d'échappement chaud. Préparer un extincteur et interdire toute source d'étincelles." }
];

export const EPIROC_REFERENCES = [
  { param: "Pression hydraulique de travail", normal: "13 MPa", alarme: "< 11 MPa", arret: "< 9 MPa" },
  { param: "Pression de pilotage joysticks", normal: "3.5 MPa", alarme: "< 3.0 MPa", arret: "< 2.5 MPa" },
  { param: "Accumulateur de freinage (Release)", normal: "12 MPa", alarme: "< 10 MPa", arret: "< 8.5 MPa" },
  { param: "Pression rampe carburant (Rail)", normal: "1600 bar", alarme: "< 1400 bar", arret: "< 1200 bar" },
  { param: "Pression d'huile moteur (à 2000 rpm)", normal: "4.2 bar", alarme: "< 3.0 bar", arret: "< 1.5 bar (Arret)" },
  { param: "Température d'eau moteur", normal: "80 - 95 °C", alarme: "105 °C", arret: "115 °C" },
  { param: "Température d'huile hydraulique", normal: "45 - 60 °C", alarme: "80 °C", arret: "90 °C" },
  { param: "Tension batterie 24V", normal: "24.5 - 26V", alarme: "< 22V", arret: "< 20V" },
  { param: "Tension alternateur tournant", normal: "27.5 - 28.2V", alarme: "< 25.5V", arret: "< 24.0V" },
  { param: "Pression pneus gonflage", normal: "6.5 bar", alarme: "< 5.5 bar", arret: "< 4.5 bar" },
  { param: "Jeu axial articulation max", normal: "1.5 mm", alarme: "> 2.5 mm", arret: "> 4.0 mm" },
  { param: "Épaisseur disques de frein min", normal: "8.0 mm", alarme: "< 6.5 mm", arret: "< 5.8 mm" },
  { param: "Épaisseur plaquettes SAHR min", normal: "12.0 mm", alarme: "< 7.5 mm", arret: "< 5.0 mm" },
  { param: "Précharge azote accumulateurs", normal: "5.5 MPa N2", alarme: "< 4.5 MPa", arret: "< 3.8 MPa" },
  { param: "Débit ventilation requis galerie", normal: "128 m³/min", alarme: "< 110 m³/min", arret: "< 95 m³/min" }
];

export const EPIROC_COUPLES = [
  { item: "Boulons de roues", filetage: "M22 x 1.5", torque: "550 Nm", lock: "Sec / Aucun", check: "Chaque poste" },
  { item: "Axes articulation pivot", filetage: "M36 x 2.0", torque: "1200 Nm", lock: "Frein filet fort", check: "250 h" },
  { item: "Vis de bride de pompe", filetage: "M16", torque: "210 Nm", lock: "Rondelle Nord-Lock", check: "500 h" },
  { item: "Chapeaux de vérins hoist", filetage: "M12", torque: "85 Nm", lock: "Frein filet moyen", check: "Révision" },
  { item: "Boulons de support moteur", filetage: "M20 x 1.5", torque: "450 Nm", lock: "Écrou autofreiné", check: "500 h" },
  { item: "Raccords tuyauterie HP", filetage: "Bride SAE 1'", torque: "90 Nm", lock: "Joint torique", check: "Fuite" }
];

export const EPIROC_KITS = [
  { interval: "50 h", desc: "Inspection visuelle globale, graissage axes, purge séparateur gasoil, contrôle boulons roues." },
  { interval: "100 h", desc: "Kit 50h + vidange de l'huile de chaîne d'entraînement, nettoyage du filtre à air primaire." },
  { interval: "250 h", desc: "Vidange huile moteur Cummins, changement filtres à huile et filtre carburant secondaire." },
  { interval: "500 h", desc: "Changement de tous les filtres carburant, nettoyage radiateur, mesure précharge accu SAHR." },
  { interval: "1000 h", desc: "Vidange huile hydraulique, vidange ponts, contrôle jeux pivot articulation, test Ansul." },
  { interval: "Révision Frein", desc: "Remplacement complet disques multilamelles, joints étriers et accu SAHR." },
  { interval: "Révision Hydro", desc: "Remontage pompe principale et de gavage avec kits joints internes d'origine." }
];

export const EPIROC_SYMPTOMS_INDEX = {
  "BRUITS": ["2.2.1.A (Essieu avant bruyant)", "2.5.1.B (Chaîne transmission bruyante)", "4.2.4.A (Claquement articulation)", "9.4.1.A (Choc silentblocs)", "10.1.3.A (Grincements axes godet)"],
  "VOYANTS": ["1.1.4.A (Alarme pression huile)", "3.1.2.A (Filtre hydraulique colmaté)", "5.3.2.A (Pression freinage basse)", "6.1.3.A (Alternateur décharge)", "8.2.1.A (DPF orange clignotant)", "11.2.2.A (Anomalie Ansul)"],
  "FUMÉES": ["1.1.2.B (Injecteur bloqué - Noire)", "1.1.5.A (Turbo usé - Bleue/Noire)", "1.1.6.A (Démarrage laborieux - Blanche)", "5.1.3.A (Étrier grippé - Grise/Friction)"],
  "FUITES": ["1.1.3.C (Fuite eau)", "1.1.4.B (Fuite huile externe)", "2.2.3.A (Fuite huile pont)", "3.3.1.A (Vérin hoist gauche)", "4.1.2.A (Vérin direction)", "7.2.1.A (Fuite refroidisseur)"],
  "MOUVEMENTS": ["2.1.1.A (La machine ne bouge plus)", "3.3.1.B (Dérive lente du boom)", "3.4.1.A (Godet ne vide pas)", "3.5.1.A (Vérin saccadé)", "3.7.1.A (Joysticks mous)", "5.4.1.A (Dévale en pente)"],
  "TEMPÉRATURES": ["1.1.3.A (Température d'eau 105°C)", "3.6.1.A (Huile hydraulique >80°C)", "5.1.1.A (Échauffement d'essieu)", "8.3.1.A (Surchauffe en galerie)"],
  "ODEURS": ["1.1.2.B (Odeur gasoil imbrûlé)", "5.1.3.A (Odeur de garniture brûlée)", "13.5 (Fuite carburant majeure)"]
};
